### ISSUE TITLE
Add documention for using NotificationHubClient

### ISSUE THREAD

**Issue by pragnagopa** [Azure/Azure-Functions#100]
Update [NotificationHub binding docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-notification-hubs) to include sample for using NotificationHubClient directly. 
Sample:

```
public static async Task Run(HttpRequestMessage req, NotificationHubClient notification, TraceWriter log)
{
   log.Info("C# HTTP trigger function processed a request.");

     string notificationPayload = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
       "<wp:Notification xmlns:wp=\"WPNotification\">" +
       "<wp:Toast><wp:Text1>NotificationHub</wp:Text1><wp:Text2>Function App Message</wp:Text2></wp:Toast>" +
       "</wp:Notification>";

       await notification.SendMpnsNativeNotificationAsync(notificationPayload, "Tag1");
}
```

**Comment by ggailey777** [comment]
@lindydonna I would suggest that usage of the NH binding is probably also low because there's no template for it and it's not exposed in the portal UI. While this specific work item might be a P2, having some better guidance around using Functions + Hubs should probably be a P1 (trigger notifications to your app using HTTP requests...or some scenario like that).
