### ISSUE TITLE
EventGridTrigger EventGridEvent requires Json 6.0.0.0?

### ISSUE THREAD

**Issue by gdodd1977** [Azure/Azure-Functions#1021]
I've created an EventGridTrigger function and am attempting to unit test. I'm creating an EventGridEvent and serializing it using JsonConvert. It's blowing up for: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

Is this really true? Does Microsoft.Azure.EventGrid.Models have a reference to a Json version that old?

**Comment by gdodd1977** [comment]
I'm actually testing Service Bus queue code, so it's expecting the message.Body to be Json.
This is what my actual test code looks like that I'm trying to use:
`var eventGridEvent = new EventGridEvent("SomeId", "SomeSubject", commPayload, "SomeEventType",
                DateTime.UtcNow, "1.0");

            var messageBody = JsonConvert.SerializeObject(eventGridEvent);
            var message = new Message
            {
                Body = Encoding.UTF8.GetBytes(messageBody),
                ContentType = "application/json",
            };`

**Comment by jeffhollan** [comment]
So the `JsonConvert` line is the one throwing the error? If so this is likely an issue with the `Microsoft.Azure.EventGrid` library which is pulled directly from their SDK

**Comment by gdodd1977** [comment]
Correct. That's where the error occurs. Who should I contact to get more info on this?

**Comment by jeffhollan** [comment]
Reaching out to them now - will let you know 👍

**Comment by gdodd1977** [comment]
Hi Jeff. Any word from the team on this?

**Comment by jeffhollan** [comment]
https://channel9.msdn.com/Shows/On-NET/Writing-Tests-for-Azure-Functions

**Comment by jeffhollan** [comment]
Thanks for the reminder. Never heard back so just re-pingd that team

**Comment by kalyanaj** [comment]
Sorry about the delay in getting back. I tried to repro this now by creating a new EventGrid trigger based function and added the following code, and the JSON serialization worked fine. I also then changed it to use JsonConvert.SerializeObject(eventGridEvent) (instead of  JsonConvert.SerializeObject(newEventGridEvent)) and that also went through fine.  The expected Newtonsoft dependency (per https://www.nuget.org/packages/Microsoft.Azure.EventGrid/) is Newtonsoft.Json (>= 6.0.8), so the 6.0.8 is only the minimum version of that dependency, and there's no maximum version limit. I am not quite sure why you are seeing the above failure, can you please check if you are seeing it with a new EventGrid trigger based function such as the below, and where the 6.0.0.0 reference is coming from?

#r "Microsoft.Azure.EventGrid"   
#r "Newtonsoft.Json"   

using Microsoft.Azure.EventGrid.Models;
using Newtonsoft.Json;  

public static void Run(EventGridEvent eventGridEvent, ILogger log)
{
    log.LogInformation(eventGridEvent.Data.ToString());

    var newEventGridEvent = new EventGridEvent("SomeId", "SomeSubject", "test", "SomeEventType", DateTime.UtcNow, "1.0");
    var messageBody = JsonConvert.SerializeObject(newEventGridEvent);
    log.LogInformation(messageBody);       
}

**Comment by gdodd1977** [comment]
So for reference, I'm not doing any of this code in my EventGridTrigger function. The function basically just receives an EventGrid Event and pushes it to a Service Bus queue.  The code I'm testing is just in a standard class library with a reference to Microsoft.Azure.EventGrid.Models. The code I pasted in an earlier response in this thread is in a Unit Test class. I'm essentially emulating what happens under the hood when a message is sent to Sb queue. If there is a better way to do this, I'm all ears.

Thanks

**Comment by kalyanaj** [comment]
Thanks for the info. I created a standalone Console application where I am using 12.0.0.0 of Newtonsoft.Json along with the same sample code above that uses EventGrid Client SDK, and I wasn't able to repro this error and JsonConvert succeeds fine. Can you please check your app.config to see if there's any incorrect bindingRedirect for Newtonsoft.Json that could be causing this issue, if not it might be worth try to add a bindingRedirect to see if that resolves the issue...

**Comment by gdodd1977** [comment]
So I added this to the proj file:

  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

And all seems good now. Thanks for your time.
