### ISSUE TITLE
Portal  Bug / Azure App Service Static IP Restrictions

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#1048]
I was performing a test by setting a rule on Azure App Service Static IP Restrictions. The test was to only allow calls from a particular IP Address. 

I've add a new HttpTrigger and the portal started to display an error message:

"the function runtime is unable to start". It gave me the idea that the platform was offline but it was actually the ip restriction even tough I haven't invoked the "Run" button.

**Comment by btardif** [comment]
@thdotnet this is somewhat by-design at the moment. The functions portal needs to be able to reach the functions runtime to perform management operations.

There is a short term workaround, you can add your ip to the ip restrictions allowed list. This way portal (running on your browser) will be able to reach the functions run-time and perform the management operations as needed.

Longer term we are working to expose functions run-time management APIs through ARM and re-targeting Portal to consume those APIs instead of talking directly to the client.

cc: @ColbyTresness
