### ISSUE TITLE
Using dot-character in project name

### ISSUE THREAD

**Issue by tobylo** [Azure/Azure-Functions#107]
Tried out the new VS tooling and created a FunctionApp (host) called 'Test.Functions' and created a new function within. Hit F5 and a command window appeared and disappeared in a flash. No output, no reason for the crash what so ever.

Tried your command line cli with the default naming, and it worked.

After a bit more trial and error it appears the one can't have a dot in the path, this breaks the runner.

I couldn't find this being mentioned anywhere and I do think that the naming convention of ProjectName.Describing.Name is quite common, others might stumble upon this aswell.

Using the 12-6-16-release of the tooling.

**Comment by lindydonna** [comment]
Yes, this is a bug in the Azure Functions CLI, which is launched by the VS tooling. The bug is tracked here, so I'm closing this issue as a duplicate: https://github.com/Azure/azure-webjobs-sdk-script/issues/1006.

Thank you for reporting--we're going to update the blog post to call this out explicitly.
