### ISSUE TITLE
Document trigger behavior when running locally

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#112]
Moved from https://github.com/Azure/azure-webjobs-sdk-script/issues/1052

Comments from Brett:

Technically they all operate like separate hosts in this case, but blobs are a little different from some of the other triggers because they don't delete the blob once they process it. That allows other hosts to process it on their own. Some examples of what would happen if you ran the same app in two machines with different hostIds (just off the top of my head):

Timer: You'd get the timer firing on both hosts.
Queues: It'd be a race to see who could dequeue the item first and only that host would run the function. This may actually be closer to what Faiz expected, and makes it even move confusing when blobs and timers behave differently.
SB: Same as queues -- one host would get the messages and the other would never see them.
It seems like you'd want two 'modes' for local development:

The HostId and all of the storage connection strings match both locally and in the cloud. This would make this running instance just like one of the ones running on an Antares machine.
The HostId and all of the storage connection strings are different locally and in the cloud. This would make the local host completely independent of the others.
Any mixing of those leads to the oddities that Faiz is seeing here.

**Comment by ggailey777** [comment]
@lindydonna What is our recommendation then? Only bind to services that are not also being used by production functions? Like recommend having a staging Blob, Queue, Event Hub etc...?

**Comment by lindydonna** [comment]
@ggailey777 Yes, or use environment variables to use a different containers, queues, etc between dev and production. It's usually much cleaner to use different accounts, however.

**Comment by securityvoid** [comment]
If you do only bind to services not being used by production, please be sure to send an error message when production is preventing the binding which says something to the effect of, "Can't bind to BLAH because FUNCTION_APP/NAME code is already listening to those actions".

Still, I'd guess this would be relatively hard to implement. 

e.g. If you had a function in production blob trigger on:
container/specific/specific/specific

And you had one developed locally that was bound to:
Container/{variable}/someother location

Do those prevent binding all the time, or only when there is a file that hits both of them? 

If you prevent binding all together I can see how you'd hit places where someone is building a new function and needs to develop it locally and therefore its a conflict. 

If you only prevent binding when there is a conflict, that sounds confusing at best and could cause issues.

I'm assuming in all of this that you allow more than one function to bind to a given storage account, because that is pretty important. I already have 3-4 apps using a single storage account for things.

**Comment by lindydonna** [comment]
@securityvoid It's not possible to enumerate other listeners to a trigger, because the triggers all operate by polling. 

If you use the same hostId when running locally and in Azure, the two hosts will cooperate with each other and only one of them will trigger on an event.

If you use different host IDs, blob triggers will trigger a function that's running locally as well as the one in Azure. 

The recommended practice when using the same storage account is to use different containers to listen on when running locally. This can be done through app settings. See https://github.com/lindydonna/CoderCards/blob/master/CardGenerator/function.json#L7
