### ISSUE TITLE
[Premium] WEBSITE_CONTENTAZUREFILECONNECTIONSTRING does not seem to support KeyVault integration

### ISSUE THREAD

**Issue by wahyuen** [Azure/Azure-Functions#1195]
**Describe the bug**
Following the documentation found at 

[https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#deploy-on-premium-plan](https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#deploy-on-premium-plan)

It stated that we needed to populate the site configuration for `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`. This seems to work fine when you put in the actual connection string, however, failed when we attempted to use the KeyVault integration syntax as described [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references)

**To Reproduce**
1. Create an Azure Functions Premium Plan
2. Navigate to the Function Application settings in Azure Portal
3. Update `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` setting to use a KeyVault reference (eg. @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/ec96f02080254f109c51a1f14cdb1931)
4. Attempting to save causes a failure.

**Expected behavior**
To be able to save `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` using KeyVault reference syntax

**Additional context**
The following error that is returned when we attempt to perform the same operation using ARM templates

```json
{  
   "code":"DeploymentFailed",
   "message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
   "details":[  
      {  
         "code":"BadRequest",
         "message":
		 "{  
		   "Code":"BadRequest",
		   "Message":"The storage URI is invalid.",
		   "Target":null,
		   "Details":[  
			  {  
				 "Message":"The storage URI is invalid."
			  },
			  {  
				 "Code":"BadRequest"
			  },
			  {  
				 "ErrorEntity":{  
					"ExtendedCode":"04203",
					"MessageTemplate":"The storage URI is invalid.",
					"Parameters":[  
					   "No valid combination of account information found."
					],
					"Code":"BadRequest",
					"Message":"The storage URI is invalid."
				 }
			  }
		   ],
		   "Innererror":null
		}"
      }
   ]
}
```

**Comment by jeffhollan** [comment]
Thanks. This was reported on Twitter the other day too and is true for consumption and premium. @mattchenderson was looking into this

**Comment by NSTA1** [comment]
I just ran into this issue _after_ doing the IaC work to get the AzureWebJobsStorage appsetting of a function app running from a key vault with an automated key rotation on each deployment... now I can't run it on each deployment because the deployments for the storage account dependencies don't (and shouldn't need to) know which storage key is in use by the key vault, which prevents me from even being able to set the app setting value to the correct storage account connection string value as a temporary work-around on each rotation.

Could I please ask for an update? :)

**Comment by jeffhollan** [comment]
Sure thing - @mattchenderson would be best person to provide and get latest on using Key Vault for the function storage account (which I believe last I heard was "fixed" but from @NSTA1 maybe wasn't or I misunderstood or there's something else here)

**Comment by NSTA1** [comment]
@jeffhollan will double check in the next day or two and confirm/deny: haven't touched this for a couple weeks.  Thanks!

**Comment by vivekkranjan** [comment]
Still it exists. Faced the same issue.

**Comment by halvardskogensjotveit** [comment]
I have the same issue.

**Comment by stepanradek** [comment]
The issue persists, but there is a workaround by constructing the connection string. The access key could be loaded as the parameter directly from key vault.

{
  "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
  "value": "[concat('DefaultEndpointsProtocol=https;AccountName=',variables('StorageAccount_Name'),';AccountKey=',parameters('StorageAccount_AccessKey'))]"
},

**Comment by jdoof** [comment]
I am facing a simlar issue is there any update on this?

**Comment by jeffhollan** [comment]
Just ping'd @mattchenderson to see if he has an update.  also I know @alexkarcher-msft is running some tests this week on storage account access and premium functions, hoping he can add this to his test matrix :smile:

**Comment by mattchenderson** [comment]
Yep - following up on this. This was supposed to have been fixed already, but clearly something is up.

**Comment by VirendraChothe** [comment]
Hope the resolution will be out soon. Waiting.....

**Comment by jacqueskang** [comment]
I'm facing the same issue

**Comment by lurumad** [comment]
I'm facing too

```json
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"The storage URI is invalid.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"The storage URI is invalid.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"04203\",\r\n        \"MessageTemplate\": \"The storage URI is invalid.\",\r\n        \"Parameters\": [\r\n          \"No valid combination of account information found.\"\r\n        ],\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"The storage URI is invalid.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
    }
  ]
}
```

Any news?

Kind regards!

**Comment by mattchenderson** [comment]
Would folks be willing to share their function app name where you're seeing this, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by maletor** [comment]
I have this issue as well. I'm going to revert to the Consumption plan for now.

**Comment by borys86** [comment]
Still not fixed? Just amazing.

**Comment by markdreyer** [comment]
Still broken, but I was able to work around this by using the following in my ARM template:

```
...
"resources": [
    {
    "name": "appsettings",
    "type": "config",
    "apiVersion": "2018-11-01",
    "dependsOn": [
        "[concat('Microsoft.Web/sites/', parameters('website'))]"
    ],
    "tags": {
        "displayName": "WebAppSettings"
    },
    "properties": {
        "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageaccount'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageaccount')),'2015-05-01-preview').key1)]",
        "WEBSITE_CONTENTSHARE": "[parameters('WEBSITE_CONTENTSHARE')]"
    }
    }
]
...
```

This creates the connection string without having to check in the storage account key or needing a KeyVault entry at all. 

Inspired by:
https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by mhoeger** [comment]
Unfortunately, this the case of a bad error message and not one issue that needs to be fixed. When the reference fails to resolve for WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, it always returns the error message `Storage Uri is Invalid` due to the nature of the App Setting.

Normally you are able to save an App Setting reference even if it is unresolvable. That is because we (on the platform) do not typically attempt to resolve the references immediately. However, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is an exception because we need to resolve this reference during site creation or update to use the connection string to create the content share on the azure files for the app. So when this fails to resolve, for one of many reasons (ex: access policies or syntax), an error surfaces that says `The Storage URI is Invalid`. Our platform team is working on a fix to surface a more helpful error message.

To understand your specific problem, you can visit the [diagnose and solve problems pane](https://docs.microsoft.com/en-us/azure/azure-functions/functions-diagnostics) in the Azure Portal. From there, look for "Key Vault Application Settings Diagnostics":
![image](https://user-images.githubusercontent.com/8888531/74071982-3cbd3900-49ba-11ea-8d30-fcb5951e62cb.png)
To see issues like this:
![image](https://user-images.githubusercontent.com/8888531/74072016-60807f00-49ba-11ea-9dcc-438850ffba67.png)

**Comment by mhoeger** [comment]
Amendment to the above: there was an issue found with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING + key vault integration + deployment slots. Details here: https://github.com/Azure/azure-functions-host/issues/5306

**Comment by fabiocav** [comment]
Closing this in favor of the issue mentioned by @mhoeger above. Please follow that issue as deployment of the fix is currently in progress and we'll provide updates there.
