### ISSUE TITLE
Queue triggered functions silently fail when StorageAccount attribute is missing at the top of the class

### ISSUE THREAD

**Issue by zmarty** [Azure/Azure-Functions#1197]
Azure Functions v2 (Windows)

Some of our functions have a either a queue input or output, like so:

```csharp
[QueueTrigger(InputQueueName)] ObjectType objectInstance
```

```csharp
[Queue(OutputQueueName)] IAsyncCollector<ObjectType> outQueueItems
```

If at the top of the class we forget to also add a StorageAccount attribute, then all of these functions fail to run silently. They show up just fine in the portal, but they just are not triggered.

```csharp
[StorageAccount("BlobStorageConnectionString")]
```

There should be a very obvious failure or even publishing error if this is the case.

If you think this is a feature request and not a bug, I disagree.

**Comment by paulbatum** [comment]
If you use a queuetrigger or queue attribute without specifying the connection property, the default behavior is to use the same storage account as the one configured with the AzureWebJobsStorage app setting. You can see this in action if you just make a new queue triggered function in VS and remove the connection property like so:

![image](https://user-images.githubusercontent.com/10663/56395229-a4698400-61ee-11e9-99dd-2563b9c7c5d3.png)

To clarify, are you saying that the problem is that when this is deployed into azure on the consumption plan, your function does not run? If so, can you clarify how you are deploying your function app?

**Comment by zmarty** [comment]
We are using the App Service Plan.

Yes, our functions do not run unless we specify the StorageAccount attribute. They fail (silently?).

Our BlobStorageConnectionString storage account from my original message is different than the AzureWebJobsStorage storage account. They are separate partially because it was unclear when we first set this up if we should have one account for AzureWebJobsStorage and another one for our other storage stuff.

**Comment by paulbatum** [comment]
Based on what you're saying, I think the system is working as designed. If you don't specify a connection string, we default to AzureWebJobsStorage. Since your queues are not created there, there is nothing to monitor and nothing to trigger. So I don't think there is a silent failure here, there is just no event to process. Does that make sense? Let me know if I'm missing something.
