### ISSUE TITLE
Deployment status endpoint for linux consmuption function apps

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#1231]
Currently there is no way to check the status of last deployment if client (functions core tools / vscode) crashes or times out before it gets the response back from Run-From-Package deployment.

Expose an endpoint where customers can query the status at a later time (on the scm site). It is good enough to have this api work for a short period of time after deployment as a best effort until the current container gets recycled for now. Eventually the deployment status should be persisted in storage / azure-files and made available for a longer period of time.

**Comment by Hazhzeng** [comment]
Since we are now supporting asynchronous deployment via POST api/zipdeploy?isAsync=true. We allow user to query the latest deployment status from GET /deployments endpoint.

Core tools and vscode will poll the deployment status from it. Implementation reference is [here](https://github.com/Azure/azure-functions-core-tools/blob/386d0e4c248bc583bb75980a4911a2c353075596/src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs#L36)
