### ISSUE TITLE
Azure Functions randomly stop

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#1236]
Hi,

I am currently facing an issue which I am finding hard to resolve or find the root cause. Randomly the Azure functions stop reading messages from EventHub/ServiceBus. 

To resolve this issue a restart is required and once that's done all messages are processed.  Also normally there are no errors in AppInsights related.

There was one instance where the ServiceBus trigger was giving an epoch error but normally the function recovers from that.

The Azure Functions are running on a Consumption Plan. Any feedback would be greatly appreciated.

Thanks!

**Comment by ConnorMcMahon** [comment]
In order to help diagnose this issue, we generally need timestamps for when these issues were encountered, as well as your function application name. If you don't feel confident sharing your function app name, you can share it in a secure way by [providing us this information.](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by GrimGadget** [comment]
So, we're having similar problems with some functions.

One in particular died yesterday from approximately 2019-06-11T17:03 to 2019-06-11T18:05 UTC.

The function Execution time/id based on the provided link is `2019-06-12T16:13:47.931,  Id=6a603e49-1a85-4dfe-b5d8-44c554001aa5`

For about an hour, the function was returing 5xx errors and recording no metrics, no messages were processing (Service Bus trigger), and no errors were reported to App Insights.

This has never happened in our test environment, but it happens every once in awhile in our production environment, so we suspect it's load related.

**Comment by RonSn0w** [comment]
Did this ever get addressed? I'm running into something very similar. When I run my Azure v2 Function based on a timer trigger of 1 hour locally it works as expected, however when I push it to Azure in my dev slot with the same settings I can't even get the instance to generate my log statement that happens before at the very start of the run method. To add to this I just did a deploy last week to the production slot which is still running swimmingly.

**Comment by ConnorMcMahon** [comment]
I'm sorry, I missed the update to this, and now the timestamp provided is outside of our log window. @RonSn0w, if you can provide similar information, I can do my best to track down this issue.

**Comment by RonSn0w** [comment]
I apologize @ConnorMcMahon , I meant to follow up with this saying I think my problem was resolved but it still appears to be not working as I would expect - and to be honest I am not really sure if this is some functional change with Azure Functions that I may have missed.

The red herring here was running through the steps to anonymously give you details on my function [here](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) *seemed* to have jump started the function to work as I would expect it to normally work. However the reality is that even though I have my function setup as a `TimerTrigger ` that runs once per hour on the hour `Run([TimerTrigger("0 0 */1 * * *", RunOnStartup = true)]TimerInfo myTimer)` the `RunOnStartup` does not appear to be working as expected when I turn off the slot for the function and turn it back on. Additionally I have logging set to state that it has started every hour but that does not seem to be following up either. 

```
telemetry = ConfigureApplicationInsights();

telemetry.TrackTrace("MyFunction.Run() - START"); 
```

On a similar function that I have **not** touched recently I see in my Application Insights logging that the untouched function is working as expected, logs appear at every hour on the hour. I know that this is not a sampling issue because the functionality that should be happening within the hour is not being executed as expected. 

Both projects are built on the .NET Standard 2.0 framework for the same external dependency reasons. Would you like me to provide details for when I manually kick off instances for both of these around the same period of time for you to look into?
