### ISSUE TITLE
Blob triggered function with long name will fail due to the naming limit of queue

### ISSUE THREAD

**Issue by LuckyWave27** [Azure/Azure-Functions#1261]
Hello experts,

As we know, if we are creating a blob storage tirggered function, it will also create a queue named "azure-webjobs-blobtrigger-yourappname" in the function storage automatically.

If we created a function named "very-very-very-very-very-very-longname-func" and a staging slot "very-very-very-very-very-very-longname-func-staging", which will definitely hit the limit of queue name(63 characters).
For example, there should be two queues created.
1.	azure-webjobs-blobtrigger-very-very-very-very-very-longname-func
2.	azure-webjobs-blobtrigger-very-very-very-very-very-longname-func-staging

In the limit of naming policy, there will only one queue named “azure-webjobs-blobtrigger-very-very-very-very-very-longname-fun” created, which cause the staging could not be triggred well.
There will not be any warning shown when you are creating a v1 function.

Besides, there are not any workaround to fix the situation.

**Comment by vutkin** [comment]
Hello all,

We have same problem.
If we deploy azure function with blobtrigger to Kubernetes and use few replicas of pod, it will cut function name due to some limit (33 chars as I see). 
So only one function could be triggered because of this bug, but another could failed with register timeout exception.

![Screenshot_10](https://user-images.githubusercontent.com/25753488/61943772-dab05f80-afa4-11e9-8324-b16d089e0164.png)

**Comment by vutkin** [comment]
Any updates?

**Comment by jhmax720** [comment]
I'm facing the same issue, any update??

**Comment by mithom** [comment]
this issue still Exists up to this day!

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
