### ISSUE TITLE
[Premium] Help us estimate costs

### ISSUE THREAD

**Issue by ishepherd** [Azure/Azure-Functions#1350]
We have a lot of Consumption Plan apps we are investigating moving them to Premium. This will increase our bills but it's very hard to estimate by how much. **Do you have any rules-of-thumb to share?**

Let's say there is **one prewarmed instance** and,

### 1. a quick function is invoked once per minute

Do these invocations have the memory-time and vCPU-time charges?

(I hope not? We already paid for ALL memory and CPU of this prewarmed instance)

### 2. load increases, so scaler starts a second instance (from cold)

Is there a per-instance charge payable for the second instance? ([my earlier question](https://github.com/Azure/Azure-Functions/issues/1292#issuecomment-537015656))

**Comment by alexkarcher-msft** [comment]
We have followed up in a separate thread

**A quick summary for anyone viewing this thread in the future:**

You should think of the pre-warmed bill as a fixed cost with every execution being billed on top of that at the premium rate. In reality it should be a bit lower, because there is some time when the instance is warming up where you are running on your pre-warmed instance and another pre-warmed instance has not yet started up.

It's also important to note that all apps in a plan share pre-warmed workers and active workers, so putting many function apps in the same plan is advantageous.
