### ISSUE TITLE
Is oData available with Azure functions ? We are looking to move our APIs to Azure but need to support reports that are oData based.

### ISSUE THREAD

**Issue by gaurav743** [Azure/Azure-Functions#1469]
I would like to know if Azure functions currently support oData. We are looking to move our APIs to Azure cloud but also need to support thousands of reports that use oData based URLs to get data. If not, till when can we expect the same feature to be available with Azure functions.

**Comment by v-bbalaiagar** [comment]
Hi @gaurav743,  Apologies for the delayed response, the issue was somehow lost in the trace. Officially, there is no support for OData endpoints in Azure Functions.
This [repo](https://github.com/aletc1/examples-odata-azure-functions#:~:text=Oficially%2C%20there%20is%20no%20support%20for%20OData%20endpoints,of%20how%20the%20final%20function%20will%20look%20like%3A) presents a workaround to implement OData in Azure Functions v2 using a custom extension method HttpRequest.ApplyTo<T>(IQueryable<T> query)

**Comment by v-bbalaiagar** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
