### ISSUE TITLE
Azure functions 

### ISSUE THREAD

**Issue by amararam** [Azure/Azure-Functions#1489]
We recommend you add feature requests to [UserVoice](https://feedback.azure.com/forums/355860-azure-functions).  This enables centralized feature requests and users the ability to vote.

if we  grant  the  read  access to azure functions it is  not supporting for azure functions.
could you please provide the solutions .

**Comment by amararam** [comment]
ok

**Comment by v-bbalaiagar** [comment]
Hi @amararam, Apologies for the delayed response. The issue was somehow lost in the trace.
Reader role gives you the right to read everything, but you cannot contribute. 
These roles are Built-in roles for Azure resources. You can find all of the Azure built-in RBAC in Microsoft docs - https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
Also, you can make a custom role for your use case - https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
