### ISSUE TITLE
[Azure-CLI] az functionapp deployment source config-zip requests/sets invalid SAS Uri in WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by anthonychu** [Azure/Azure-Functions#1566]
https://github.com/Azure/azure-cli/issues/13070

**Comment by miiitch** [comment]
Hi, it's almost a year, and the issue is still here. When do planned to fix it? Do you have a workaround?
Regards,

**Comment by gzuber** [comment]
Hi @miiitch -- really sorry for the delay here. This should be fixed with https://github.com/Azure/azure-cli/pull/17722, so I'm going to go ahead and close this. If you have any more trouble with this issue or the fix doesn't work as expected, please ping me directly and I'll see what we can do. Thanks!

**Comment by miiitch** [comment]
Thanks!
