### ISSUE TITLE
Allow non-public constructor for Function DI

### ISSUE THREAD

**Issue by Timovzl** [Azure/Azure-Functions#1603]
A (non-static) Function's constructor that is used for dependency injection must currently be public.

Sometimes a Function has dependencies that (even as interfaces) are internal to its own project. As parameters of a public constructor, they are forced to become public, even though that is not the correct visibility modifier for them.

Non-public constructors (particularly internal ones) are the natural solution.

**Comment by v-anvari** [comment]
Hi @Timovzl , Apologies for the delayed response, This scenario is by-design, the functions require the classes to be public constructor. This is necessary only for the functions target. The implementation of the services you are using need not be public, because those could be internal or private without a problem today. You can register all of the those without without issues, but the targets of the functions that class that we used initiate for the functions we do require those to be public.

Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.

**Comment by Timovzl** [comment]
@v-anvari I do not feel like the issue has truly been addressed.

You have provided a workaround, i.e. injecting public interfaces backed by non-public implementations. That is possible, yet it still forces those interfaces to be public, even if that is not their natural or intended visibility.

What is the _reason_ for requiring public constructors on a Function class? Because unless there is a solid reason, I am suggesting that the restriction be removed, since there is a clear disadvantage to it.

**Comment by v-anvari** [comment]
Hi @Timovzl , This won't be possible due to the design limitations. There are couple of reasons due to which the developers have taken this call. For one instance, ActivatorUtilities functionality provided by the framework to instantiate the user's class, and this requires the type to have a public constructor
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L236

**Comment by Timovzl** [comment]
@v-anvari Following the behavior of `ActivatorUtilities` does indeed seem logical and fairly definitive. Thanks for clarifying.

Out of curiosity, do you know where I might find information about why that design was chosen for `ActivatorUtilities`, or general reasons for opting for public constructors only? I understand the cause now, but I would also like to understand the reasons.

**Comment by v-anvari** [comment]
Hi @Timovzl , Apologies, I am not sure if that's documented anywhere.

**Comment by Timovzl** [comment]
Ok, thanks for your replies.
