### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE is setted again after new deploy

### ISSUE THREAD

**Issue by mviegas** [Azure/Azure-Functions#1606]
Hi guys.

I'm having an issue with a function app running on windows consumption plan. 

I removed the setting `WEBSITE_RUN_FROM_PACKAGE` from my configuration directly in azure portal, as my functions performs some quick disk writing and needs write access to wwwroot.

But every time a new version is published from Visual Studio 2019, this setting is created and setted to `1` again and, therefore, my function does not execute as expected, since wwwroot becomes read-only with this setting.

Is this a bug or is this by design? If it's by design, would you have any suggested workaround so that new deploys don't reset this setting?

Thanks in advance!

**Comment by v-bbalaiagar** [comment]
Hi @mviegas, Apologies for the delayed response. yes, It is by design - `WEBSITE_RUN_FROM_PACKAGE` is our default deployment option - this gives better performance and eliminates issues with file watchers during deployment. Please go through the [document](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package) for more information. Let us know if this help.

**Comment by balag0** [comment]
@vijayrkn Is there a way to configure VS to not use Run-From-Pkg?

**Comment by vijayrkn** [comment]
For function app windows, we provide 2 options: 1) Deploying using Web deploy (when the run from package checkbox is unchecked) & 2) Using Zip deploy and run from package. 

You can uncheck the checkbox & this will allow publishing the files without running from the package. Hope this helps.

**Comment by v-bbalaiagar** [comment]
Hi @mviegas, Can you please confirm were you able to find a solution here. Do let us know if you have any further queries.

**Comment by mviegas** [comment]
Hi @v-bbalaiagar it's been so long that, honestly, I do not remember what I did to solve this. 

I also have no further queries on this, so I'm closing this issue. 

Thank you!
