### ISSUE TITLE
Blob documentation lists unsupported output types ICollector and IAsyncCollector

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#162]
You can't actually use `ICollector` or `IAsyncCollector` with the blob binding -- yet the doc lists them: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#output-usage. We need to remove those two bullets.

**Comment by ggailey777** [comment]
Removed those too collection items. Also, changed the instance of Foo*

**Comment by mosharafMS** [comment]
It seems the reference returned back again on https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#output 
 
It states "In async functions, use the return value or IAsyncCollector instead of an out parameter." 

however when tried it, getting the error message 
Microsoft.Azure.WebJobs.Host: Can't bind Blob to type 'Microsoft.Azure.WebJobs.IAsyncCollector`1[System.IO.Stream]'

**Comment by alexgman** [comment]
Is this possible yet? How do we use IAsyncCollector with a blob output?

**Comment by mcollier** [comment]
@ggailey777 FYI
