### ISSUE TITLE
Allow scheduled delivery of queue messages

### ISSUE THREAD

**Issue by itaysk** [Azure/Azure-Functions#169]
I'd like to suggest adding an option to schedule delivery for messages in queue output.
This is supported by both Azure Queue and Service Bus Queue, but the run time has to pass the delay parameter.

**Comment by slideep** [comment]
I assume you are referring for a way to do this in `serviceBus` -binding at function-level in `function.json`?
Now I guess the support for custom input/output bindings is out of reach at the moment so that option
doesn't fly yet - doing your very own custom binding or extending `ServiceBusAttribute`.

At least with C# & Node.js (and why not in F#) the Service Bus queue output already supports this e.g. if you create and put multiple messages e.g. to `IAsyncCollector<T>` or create `out BrokeredMessage`. Within your outgoing message(s) you can control the scheduled enqueuing time:

```csharp
outgoingMessage.ScheduledEnqueueTimeUtc = DateTimeOffset.UtcNow.AddSeconds(10)
```

Working fine to add some exponential backoff and random constant delay when things are flooding in... Good luck!

**Comment by mathewc** [comment]
Yeah, while you can control the schedule time on the SB message, the same knob isn't present on CloudQueueMessage for Azure Queues. If you're writing a C# function, you can change your function parameter to bind to a CloudQueue and we'll had your function the queue. You can then call the Add method yourself passing in your invisibility timeout.

I realize that you're asking for a way to make this more automatic, but the above is all you can do for now.

**Comment by itaysk** [comment]
@mathewc @slideep 
I am using Azure Queues not SB, and PowerShell.
I am not asking for a "nicer" way, just anything that'll work. It is possible with PS?

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1465
