### ISSUE TITLE
Not able to download publish profile on modern azure

### ISSUE THREAD

**Issue by orta** [Azure/Azure-Functions#1702]
### Classic
![Screen Shot 2020-08-27 at 6 33 14 PM](https://user-images.githubusercontent.com/49038/91501499-c0c20a00-e893-11ea-832f-134081cf3022.png)

### MS Dogfood Azure
![Screen Shot 2020-08-27 at 6 33 25 PM](https://user-images.githubusercontent.com/49038/91501476-b4d64800-e893-11ea-94c1-4f157cac5cfd.png)

**Comment by ImaduddinAMajid** [comment]
I faced the same issue

**Comment by ehamai** [comment]
Hey @orta and @ImaduddinAMajid, so we ended up disabling the "Get publish profile" button for Linux Consumption Function apps because FTP and Web Deploy aren't supported for them and it ended up confusing a lot of users.  The credentials themselves are still useful for doing Zip Deployments to your app, but typically users of zip deploy are also using other clients which are downloading the profile behind the scenes so that you don't have to parse it yourself.

If you're not using one of those clients, would you mind helping me to understand how you're using the profile in your case please?

**Comment by ImaduddinAMajid** [comment]
I am using GitHub actions for zip deployment thus need the publish profile. [functions-action](https://github.com/Azure/functions-action)

**Comment by orta** [comment]
Same

**Comment by ehamai** [comment]
Got it.  Thanks for clarifying @ImaduddinAMajid and @orta .  I think we were expecting GitHub Actions users for Functions to be using the Functions CLI to set it up, but that was obviously a bad assumption.  @takyyon can you make sure we re-enable this for now please?

Also just for my own understanding, if we had GitHub Actions support for Function apps in the Azure portal (which automatically creates a workflow file and wires up the secrets for you), would you prefer to use that?  Or would you rather continue copying it manually as you're doing today?

**Comment by ImaduddinAMajid** [comment]
Yes, that would be helpful. I would prefer to do it automatically rather than manually copying the secrets from the portal.

**Comment by orta** [comment]
I'm cool with the opaque secret like how static web apps does it 👍🏻

**Comment by ehamai** [comment]
Got it.  Thanks for the feedback!  BTW looks like @takyyon was able to slip in the publish profile fix into our next deployment so it should come back online sometime next week.  Sorry for the troubles guys.  Given that he's fixed it I'm going to close it for now.  If you're still seeing this issue after next week, please feel free to reactivate.
