### ISSUE TITLE
Cannot add files online in azure functions new interface

### ISSUE THREAD

**Issue by eliteapps** [Azure/Azure-Functions#1703]
I am able to add new files like project.json in Azure functions old (classic) interface. But Adding new files is not available in new interfance.

**Comment by tim-at-software-forge-co-uk** [comment]
Yeah! I need to be able to upload files directly, partly because the Azure Function App new project wizard in VS errors out for me, so I can create a project that can be deployed from VS. I am just uploading binaries manually and calling them from my Azure run.csx script. Now my workaround is being taken away... grrrrrrrr

**Comment by v-anvari** [comment]
Hi @eliteapps / @tim-at-software-forge-co-uk , The upload option in your Function will let you upload files to your function in the new interface.

![image](https://user-images.githubusercontent.com/66122429/122065392-8835f180-ce0f-11eb-85c7-d7de9583f3ff.png)

Closing this issue as the functionality is present, please feel free to reach back to us in case of any issues.
