### ISSUE TITLE
How to monitor Azure Functions outside the portal?

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#171]
Is there an API for monitoring functions? Lets say I would like to build my own portal in our Admin area where I could see if the functions are up and ranning(ie when was the last function execution and the result). Thank you.

**Comment by slideep** [comment]
It's not documented yet (or I couldn't find it) at Kudu's wiki but the API's are surely there since the functions dashboard uses them:
https://your-functions-app.scm.azurewebsites.net/azurejobs/#/functions

and by using basic auth (or bearer token) you can make actual requests:

https://your-functions-app.scm.azurewebsites.net/azurejobs/api/functions/invocations/recent?limit=11
https://your-functions-app.scm.azurewebsites.net/azurejobs/api/functions/definitions?limit=11

At least managed to verify these with Fiddler, for more up-to-date function monitoring service endpoints, I'd stalk in the mean time:

https://github.com/projectkudu/AzureFunctionsPortal/blob/master/AzureFunctions.Client/app/services/function-monitor.service.ts

**Comment by skorunka** [comment]
Very helpfull! Thank you, that's what I wal looking for.
