### ISSUE TITLE
Multiple Function Apps not getting deployed

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/Azure-Functions#1710]
I have three function apps in my solution as shown below:

![image](https://user-images.githubusercontent.com/6519992/92495399-b5cc7b00-f1ab-11ea-9a4c-eea05fb777e0.png)

I created the build & release steps to deploy these 3 function apps to the same app service plan. On running the build, it created the artifact with these function app solutions in zip:

![image](https://user-images.githubusercontent.com/6519992/92497715-8f5c0f00-f1ae-11ea-9452-0253b0c14d32.png)

and I see these function apps being deployed:

![image](https://user-images.githubusercontent.com/6519992/92496057-823e2080-f1ac-11ea-8596-779c662bbde8.png)

On clicking the function app, I see function in one of the function apps. but not in the other two:

![image](https://user-images.githubusercontent.com/6519992/92498139-1dd09080-f1af-11ea-8ebf-1f844595510b.png)

What am I missing? Please let me know if you need more details. Thank you!

**Comment by balag0** [comment]
I can see zip deploy was invoked for all the function apps.
Can you check if the artifacts look right (includes the expected functions with the right folder structure)

I also see none of the 3 function apps are using these 2 appsettings. Is that intentional?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentazurefileconnectionstring

**Comment by xyz92** [comment]
@balag0  the artifacts looks correct - It was intentional. After reading https://developercommunity.visualstudio.com/content/problem/664220/deploying-multiple-function-projects-to-multiple-f.html, I removed these 2 properties because this is not a premium plan and adding these properties added functions in incorrect function apps.

**Comment by v-bbalaiagar** [comment]
Hi @lipalath-ms, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by v-bbalaiagar** [comment]
Hi @lipalath-ms, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
