### ISSUE TITLE
[UX] - The new function app UI is a step backwards in immediate usability

### ISSUE THREAD

**Issue by StingyJack** [Azure/Azure-Functions#1751]
With one click in the classic "Tree view" I could view the invocation logs/history, now to reach the same, its at least three clicks and screen changes.

These invocations are the primary reason for visiting this UI, and now I cant get to them as fast as before.  Why would we accept this change as any kind of improvement?

**Comment by btardif** [comment]
FYI @ehamai

**Comment by ehamai** [comment]
Hi Jack, thanks for the feedback.  Yeah I think in some ways I agree that it is a step back from from the old experience in terms of the overall navigation model especially for people who just want to see their function logs.  While there is always going to be a set of developers who like the old management model, we also got a ton of feedback from customers that said they were confused because it didn't look and feel like the rest of Azure.

That said, one thing that we're actively working to improve is how easy it is to get an overview of how all of your functions are doing in your app with less clicks.  This is probably one of the largest pieces of feedback that we've been getting and I think that once we have this, it will actually be a big improvement over the old experience.

**Comment by StingyJack** [comment]
@ehamai - I'm sure it can be made to feel more like the rest of Azure without increasing the amount work the users have to perform on a hot path. 

Please keep in mind that making the program look and feel consistent is less important than maintaining or improving functionality. How many people whine for a dark mode immediately on everything now? At an extreme but legitimate example, a dark mode feedback can have 7k votes, but will always be less important than fixing a regression that's breaking production for any single customer.

**Comment by ehamai** [comment]
Thanks @StingyJack, yeah I see what you mean.  In this case we made a call and so far we've gotten a lot of good feedback on it.  And while it's definitely not perfect by any means, we're still pushing forward on making improvements.

**Comment by StingyJack** [comment]
@ehamai - I just want to emphasize this isnt a complaint in the style of "who moved my cheese".  In the last 4-5 years, a lot of **problems** being reported to MSFT by users are being interpreted as "cheese movement _feedback_" and they get effectively dismissed. Requiring the users to perform more actions to get to the logs than were needed before is a productivity problem that can also become a production supportability problem. Its not a cosmetic complaint.

Perfection is a fools errand.
