### ISSUE TITLE
Scoped Service getting cross object value pollution in Azure Function class

### ISSUE THREAD

**Issue by abhaldar** [Azure/Azure-Functions#1764]
We are using scoped life time for our services and observing while injecting it in function class constructor it is getting pre-populated value in the properties of that class in place of getting a new object per execution of a function in that class. And we do not have any default value for those properties.

public interface ISampleService {
   public SomeStruct Object { get; }
}

Example
services.AddScoped<ISampleService, SampleService>();

public class FunctionA
{
    public FunctionA(ISampleService service)
    {
            service,Object -> should be null but it is not.
    }

    [Function("somefunction")]
    .............
}

Are we not expecting that per execution of "somefunction" we should get service.Object as null? as inside SampleService as we by default not allocating any value to this.

Also the object which is getting populated here is only allocated to SampleService class directly at some other function in another class which is not even via DI. So this case is diluting our entire architecture of using DI efficiently.

**Comment by v-anvari** [comment]
Hi @abhaldar , Apologies for the delayed response, let us know if you were able to find a solution. In order to support scoped services we need to change some of the methods. First we need to create and store an IServiceScope instance for each function invocation, so that we can share the same scope for the same function invocation. 

Here is a demo explaining how scoped services work - https://channel9.msdn.com/Shows/On-NET/Leveraging-the-Dependency-Injection-support-in-Azure-Functions#time=20m32s

Let us know if you have any further queries

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
