### ISSUE TITLE
Dotnet can not bind TimeSpan 

### ISSUE THREAD

**Issue by MhAllan** [Azure/Azure-Functions#1768]
I have this function failing with error **Invalid cast from 'System.String' to 'System.TimeSpan'**
```csharp
[FunctionName("GetTime")]
public async Task<IActionResult> GetTime([HttpTrigger(AuthorizationLevel.Function, "get",
Route = "{Start}/{End}")] [FromRoute] TimeRequest request, CancellationToken ct)
{
     return new OkObjectResult(request);
}

public class TimeRequest
{
     public TimeSpan Start { get; set; }
     public TimeSpan End { get; set; }
}
```

Same error for this
```csharp
[FunctionName("GetTime")]
public async Task<IActionResult> GetTime([HttpTrigger(AuthorizationLevel.Function, "get",
Route = "{Start}/{End}")]
HttpRequest request, TimeSpan start, TimeSpan end, CancellationToken ct)
{
     return new OkObjectResult(start);
}
```
While in Asp.Net Core we don't face issues

**Comment by v-anvari** [comment]
Hi @MhAllan , Apologies for the delayed response. The casting error is because the TimeSpan is expecting a Time Interval rather than a string. By parsing the string representation of a TimeSpan value, you can use the Parse and TryParse methods to convert strings that contain time intervals to TimeSpan values. You can find the examples in the [document ](https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=net-5.0#instantiating-a-timespan-value)here.

**Comment by MhAllan** [comment]
I don't know how is this a solution to the problem. that is a solution for my manager not for this problem.

**Comment by v-anvari** [comment]
Hi @MhAllan, I will re-open the issue for you. Are you asking us to correct the code for you? Because I have shared the examples in the above comment in a link for you to understand the specs. Let us know how can we help you.

**Comment by MhAllan** [comment]
@v-anvari I am just letting you know that your framework should actually bind TimeSpan from a string as this is the common way people want to communicate a timespan between services.

**Comment by v-anvari** [comment]
Hi @MhAllan , This scenario is by - design and as the Time span is expecting a time interval, it is expected to be parsed as a string.
