### ISSUE TITLE
 Azure storage POST queue item sometimes processed very slow (up to 1.5 minutes)

### ISSUE THREAD

**Issue by Haletski** [Azure/Azure-Functions#1792]
We using HTTP trigger function to add a message to the queue. In general to process such requests it takes 10-20ms but sometimes, maybe depending on a high load, it could take up to 1.5 minutes or even more. HTTP trigger function retrieves string from the query parameter and writes it to the queue. This execution time is crucial for us and it's not clear why so simple request takes too much time.

Here is an example of a long-running request.
![image](https://user-images.githubusercontent.com/30402551/100336311-11f2ae80-2fe7-11eb-98bd-e59b518f023f.png)

**App Details**
Azure function version: 2
Location: UK South
App Name: func-dataforseo-dave-preprod
.NET Core 3.1:
Storage account: stdavemainpreprodenv
Plan: App service plan
Date: from 2020-11-25 18:00 UTC to 2020-11-26 04.00 UTC

**Comment by yarsavenkov** [comment]
Hi Pavel! 

I am writing on behalf of DataForSEO and I am super interested to help you out :)

Could you provide me with some details of your project, so we can localize the issue, find possible reasons and eventually resolve it? 

Please, provide me with the details of the request that is taking too long time to be completed. I want to checker whether everything is going smoothly on our end and continue the investigation. 

You can drop a line to our customer support at DataForSEO and hand the details over them, or just let me know on LinkedIn, I sent you an invite.

If it’s more convenient, let’s continue discussing the issue here, but I will need some account details to determine the problems.

**Comment by v-anvari** [comment]
Hi @Haletski , We have checked the backend logs and we see that there were high Cpu load during last month. Let us know if the function App is still functional so that we can check into the errors further. Looking at the latest report, the App is having failure rate of 100% with different exceptions

**Comment by Haletski** [comment]
@v-anvari Hi. So function app is still functional and it will be good if you can provide any further details

**Comment by v-anvari** [comment]
Hi @Haletski , We are able to check only the latest data and I see mostly "System.Web.Http.HttpResponseException" and most of the times when overall instance memory was high, the app was running on an instance that had less than 2 GB of total RAM. Out of the total physical memory, some memory is used by System services and other infrastructure processes to run as well. If this is a production app and your app has high memory requirement, consider scaling up to the next tier.

I see there are different functions running in your App with different triggers. Can you give us an invocation id and time stamp and function that you want us to particularly check. Which function is causing you the trouble. 

Go to App Service Diagnostics to scale up the App Service instance.

Alternatively, follow the instructions below.

Navigate to the application in the Azure Portal.
Select the "Scale up (App Service plan)" tab from the left sidebar menu.
Select a pricing tier that fits the performance and feature needs for your application.
Click "Apply" to apply the pricing tier to the application.

**Comment by v-anvari** [comment]
Closing this issue as there is no response, please feel free to reach back to us   in case of any further queries related to this issue
--
