### ISSUE TITLE
Under the Azure functions option for .Net is not available 

### ISSUE THREAD

**Issue by sudhirbabu1979** [Azure/Azure-Functions#1807]
Hi team ,While creating the Azure function only for .Net core option is available and no option for classic .Net .i believe this is missing in the existing new version of Azure portal.

**Comment by Abdelhak-Bahri** [comment]
It's because Azure functions has different runtime versions. The last version now is 3.x and app created on azure portal or Azure Cli are created on the last runtime version(3.x). Azure function runtime version 3.x support functions written on C# only via NET Core 3.1 as it's mentioned in this table : 

![image](https://user-images.githubusercontent.com/5613412/104255097-935bae80-5478-11eb-8e57-8f55aa43bdff.png)
Source : https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#languages

_By default, function apps created in the Azure portal and by the Azure CLI are set to version 3.x. You can modify this version as needed. You can only change the runtime version to 1.x after you create your function app but before you add any functions. Moving between 2.x and 3.x is allowed even with apps that have functions, but it is still recommended to test in a new app first._

source : https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#creating-1x-apps

Just create your function app using any language supported on azure portal and change it later to version 1.x . on azure function pages chose "Configuration" page under "settings" submenu . Change the value of "FUNCTIONS_EXTENSION_VERSION" from "~3" to "~1" and Save . Then , you can create functions using all available languages on Runtime Version 1.x of Azure functions.

![image](https://user-images.githubusercontent.com/5613412/104254886-1fb9a180-5478-11eb-9d34-5e747b19bbfd.png)

**Comment by v-bbalaiagar** [comment]
Hi @sudhirbabu1979, Apologies for the delayed response, Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by sudhirbabu1979** [comment]
Yeah please close the issue.

**Comment by v-bbalaiagar** [comment]
Hi @sudhirbabu1979, Closing this issue, In case of any further concerns regarding this issue, please feel free to re-open the issue.
