### ISSUE TITLE
[Premium] How to prevent noisy neighbors in Premium Plan

### ISSUE THREAD

**Issue by dulems** [Azure/Azure-Functions#1865]
**Describe the bug**

We are currently using App Service Plan for our function apps. We ran into an issue where a function app was using too much CPU and broke other apps in the same app service plan. Would moving to Premium plan address noisy neighbor issues? We cannot use Consumption plan because our apps run on Docker containers.

**Comment by v-anvari** [comment]
Hi @dulems, If you want to avoid noisy neighbors, the answer is just to make sure your app is the only one running on your app service plan.

**Comment by dulems** [comment]
Hi @v-anvari, I recently learned that each function app in a Premium plan has its own app service plan. Is that correct?

**Comment by v-anvari** [comment]
Hi @dulems , for a given VM, they're dedicated, You're not sharing the worker with others. But there are other infrastructure components that are multi-tenant

**Comment by dulems** [comment]
Hi @v-anvari : I don't think I understand the response. To be specific: If my plan is Premium and I have two function apps A and B deployed in this premium plan, will this setup suffer from noisy neighbor issues if function app A uses too much resources?

**Comment by balag0** [comment]
Yes, both apps will run on the same vm.
It is not necessary to have each app in its own app service plan. you will have the option of selecting an exsiting app service plan or creating a new plan when creating a new app.

This might be helpful as well - https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#organize-functions-for-performance-and-scaling

_If you run multiple function apps in a single Premium plan or dedicated (App Service) plan, these apps are all scaled together. If you have one function app that has a much higher memory requirement than the others, it uses a disproportionate amount of memory resources on each instance to which the app is deployed. Because this could leave less memory available for the other apps on each instance, you might want to run a high-memory-using function app like this in its own separate hosting plan._

**Comment by dulems** [comment]
Thank you, @balag0 !
