### ISSUE TITLE
Unable to use AppSetting % Binding For ServiceBusTriggerAttribute.Connection

### ISSUE THREAD

**Issue by jimmytricks** [Azure/Azure-Functions#1874]
# Description

I have a boiler plate Service Bus Trigger function. I want to use an app setting binding with %. I have a local.settings.json with these values so that I can test locally by connecting to the service bus. The % bindings get swapped out for QueueName but not for ServiceBusName.

Service bus app:

```
[FunctionName("ExampleFunc")]
public static void Run([ServiceBusTrigger("%QueueName%", Connection = "%ServiceBusName%")])
```

local.settings.json: 

```
{
  "IsEncrypted": false,
  "Values": {
    "QueueName": "queueName",
    "ServiceBusName": "Endpoint=sb:...."
  }
}
```

## Actual Behavior
1. Error thrown: 

_Warning: Cannot find value named '%ServiceBusName%' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger'._

## Expected Behavior
1. Expect that both QueueName and ServiceBusName are retrieved from local.settings.json

**Comment by v-bbalaiagar** [comment]
Hi @jimmytricks, You should be able to accomplish this without a percent sign, because by default the connection property is a redirection to a different configuration source. But the difference here is that in the queue name you have to use the actual value provided as part of the configuration.
If you want this to be a redirection instead and look up that information from a configuration source you can use the percent syntax. You cannot specify a raw connection string in the connection property.

**Comment by v-bbalaiagar** [comment]
Hi @jimmytricks, Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
