### ISSUE TITLE
Msftbot better than stale bot, but still needs to be taught about fairness

### ISSUE THREAD

**Issue by StingyJack** [Azure/Azure-Functions#1936]
The msftbot needs to give the author an equal time to respond as it took for a contributor or member to respond to them.

So if it took 238 days for a member to respond, the bot should wait 238 days for the author to respond before considering the issue abandoned and closing it.

That is a real example, and is a long time to respond. Making the max wait as 90 days and the minimum 7 would be more reasonable and fair, but it's not fair to only give 7 days for the author to notice after they waited so long for even an acknowledgement.

**Comment by v-anvari** [comment]
Hi @StingyJack , Please consider our apologies, we are working on the bot response. As the older issues were some how lost, We have a new team members to look into older issues and resolve them. Though we understand all the issues are important, Some older issues are stale because of newer versions and fixes that were made this year. The user is always welcome to re-open an issue if the query is not resolved. The reason the bot closes it sooner is to keep the repository clean, but also giving the team a chance to look at new issues with proper labels. 

We apologize for any in convenience caused. But, we will surely consider the feedback and we are working on the bot response. Closing this issue as this issue is acknowledged and is being worked upon.

**Comment by StingyJack** [comment]
@v-anvari  its not the response, its the timing. Someone waiting 200 days for an answer should be getting more than a week to respond. 

Dont fall into GitHub's "Outdated" trap/pattern. That is a bad feature that leads to code quality issues.
