### ISSUE TITLE
Azure FunctionApp became inactive, there was no change/deployment

### ISSUE THREAD

**Issue by sureshtadisetty** [Azure/Azure-Functions#1945]
**Describe the bug**
We've an Azure FunctionApp with a bunch of HttTrigger, TimerTrigger and ServiceBusQueueTrigger functions.
On Fri (06/25) FunctionApp went to inactive state (functions were not executing).
FunctionApp restart fixed the problem.
I unable to find any useful logs to understand this issue. Need help to understand what went wrong here.

AzureFunction execution id:
2021-06-29T17:16:41.344 [Information] Executed 'OnConfigChangePullRequestCreatedSB' (Succeeded, Id=8d210d1c-e521-4bed-b3b1-1a632eb895c0, Duration=4034ms)
Region: WestUS

**Screenshots**
![image](https://user-images.githubusercontent.com/3320158/123840591-5cad0f80-d8c3-11eb-8da5-1760cd0d2466.png)

**Comment by sureshtadisetty** [comment]
Graph is for "Function Execution Count" Sum

**Comment by v-anvari** [comment]
Hi @sureshtadisetty , Thank you for the details, we shall check the backend logs and update as appropriate

**Comment by v-anvari** [comment]
Hi @sureshtadisetty , We have checked the backend logs, we see that at the below time stamp app_offline.htm file was created by the host. During a Function app deployment, Functions Host may create an app_offline.htm file to shutdown the Host. This is done to ensure that no assembly files are in use while a deployment is ongoing. Once the deployment completes, the Functions Host removes this app_offline.htm file. However, if the delete operation for app_offline.htm failed, or if the Functions Host did not catch the delete event, your Function app may stay in an offline mode.

To mitigate this, you could try -

- Deleting the app_offline.htm file using SCM (kudu) site, if it is present.
- If the offline file is not present, restarting the Function app manually.

In order to avoid such deployment issues, we recommend that you use Run-From-Package as a deployment method. Run-From-Package does not require creating an offline file, and is more resilient to such issues.

Your application process was restarted as the host.json or function.json was manually changed from Portal, Kudu, FTP or via App Service Editor. It will restart the Function App host in order for the new values to be loaded. Around 6/25/2021 11:00:00 PM (UTC), your application process was restarted as application environment variables changed. This can most likely occur due to update in app settings or swap operation.

- 2021-06-25T23:02:59

**Added env vars: WEBSITE_RUN_FROM_PACKAGE, APPSETTING_WEBSITE_RUN_FROM_PACKAGE Removed env vars: WEBSITE_ENABLE_SYNC_UPDATE_SITE, APPSETTING_WEBSITE_ENABLE_SYNC_UPDATE_SITE**

- 2021-06-25T23:04:09

**Added env vars: WEBSITE_ENABLE_SYNC_UPDATE_SITE, APPSETTING_WEBSITE_ENABLE_SYNC_UPDATE_SITE Removed env vars: WEBSITE_RUN_FROM_PACKAGE, APPSETTING_WEBSITE_RUN_FROM_PACKAGE**

`2021-06-25 23:04:41.2564330 -	File change of type 'Changed' detected for 'D:\home\site\wwwroot\app_offline.htm'`

**Comment by sureshtadisetty** [comment]
Ah great! this is very useful info.
Thank you for investigating @v-anvari! Appreciate it! 

This variables are not modified by us. Looks like there is some conflict in deployment method.
Some process tried to set RunFromPackage and another process tried to reset it to EnableSyncUpdate method in about 1 min time gap.
We deploy using EV2 task through ADO release pipeline. I'll checkout where is the conflict.

**Comment by sureshtadisetty** [comment]
@v-anvari couple of more questions:
1 - why would this not happen with every deployment?
2 - is there a place or logs I can see this action sequence myself? 
I'll try to fix deployment method conflict, and wondering how can I check if its fixed.

**Comment by v-anvari** [comment]
Hi @sureshtadisetty , 
1. These events depends on the traffic, if there is traffic, then sometimes it fails to start the host.
2. You can track these events in activity logs

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
