### ISSUE TITLE
VS2015 Functions preview template AppSettings

### ISSUE THREAD

**Issue by JWiersema** [Azure/Azure-Functions#198]
- For issues with the Functions Visual Studio tooling, provide detailed steps to reproduce, including details about your environment (OS, VS version, etc)
I'm using VS2015 Update 3 on windows 10 enterprise with the tools from 6 december. I have below appsettings.json file. These appsettings do not appear in the app service when I publish from VS2015 to a new app service. Mysteriously the appsettings AzureWebJobsDashboard and AzureWebJobsStorage do get deployed (used in the sample here: https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/ )

Besides this I noticed that you need to manually save the project.json file again in order for the Function to get the nuget packages. Might be nice to put that in the tutorials if it's not a bug.

appsettings.json
{
  "IsEncrypted": false,
  "Values": {
    "Make:SiteUrl": "myurl",
    "Make:AppId": "aguid",
    "Make:AppSecret": "asecret"
  }
}

**Comment by lindydonna** [comment]
appsettings.json is only used locally, not in Azure. The reason you saw those settings in Azure is because they are set automatically when you create a Function App.

For the other issue, there is a bug where Visual Studio is publishing project.lock.json on publish. There's a workaround in this issue: https://github.com/Azure/Azure-Functions/issues/175
