### ISSUE TITLE
Switch Azure Function OS from Windows to Linux using ARM templates

### ISSUE THREAD

**Issue by vakuras** [Azure/Azure-Functions#2112]
Our function are running on Windows with a Premium consumption plan -
Is there a simple way to switch the OS from Windows to Linux, prefferably using an ARM template?

**Comment by balag0** [comment]
The properties to use are https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#linux

But due to some backend limitations it is not possible to switch the OS of the app at this time. Only option is to create a new app and you might have to create the new app in a new resource group (one that doesnt have any windows apps in it already)
