### ISSUE TITLE
EntityFrameworkCore.Tools (version 3.1.17) stops Application Insights correlation for Azure Function Apps and no dependencies reported

### ISSUE THREAD

**Issue by DeepMalh44** [Azure/Azure-Functions#2134]
Hi All,
I am referring to the issue reported in July 2021 : https://github.com/dotnet/efcore/issues/25339 (
@bricelam from Entity Framework team had some suggestion but not sure if lowering the version is the only option).

EntityFrameworkCore.Tools stops Application Insights correlation for Azure Function Apps.

We are using this and still having the same issue and seems like from above thread that they want this to be reported here on Azure-Functions Github, can someone please let us know if there is any resolution on this as Telemetry is missing in Application Insights and this is becoming really difficult for the Client support team to identify bottlenecks as dependancy telemetry is missing.

Also here is the WORKAROUND suggested in the community and unfortunately it seems its been more than 1 year+ and this issue is not resolved by Microsoft:
https://github.com/Azure/Azure-Functions/issues/1613

Appreciate your help.

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @RohitRanjanMS Could you please look into this?

**Comment by RohitRanjanMS** [comment]
It is always going to be a challenge due to different version of Nuget packages. Microsoft.EntityFrameworkCore.Tools  3.1.17 works well with Functions v4 but the moment you upgrade to latest version (7.0.0) it fails with the following error. 
[2022-11-22T09:14:33.989Z] The 'Finish' function is in error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

I would recommend running function in [isolated](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) worker process. There won't be any conflict.
