### ISSUE TITLE
[Premium] Recommendation for using WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by tbasallo** [Azure/Azure-Functions#2138]
Diagnose issues recommends to use WEBSITE_RUN_FROM_PACKAGE for a number of reasons.

Azure DevOps (ZipDeploy) removes this settings (as part of the PowerShell script).

There seems to be some open issues around WEBSITE_RUN_FROM_PACKAGE and various items (perf, storage billing, etc.).

What's the current recommendation for:

Azure Function v3, .NET Core 3.1
ZipDeploy via Azure DevOps
Premium Plan

Does that change for .net6 and v4?

**Comment by balag0** [comment]
Yes WEBSITE_RUN_FROM_PACKAGE is recommended. same applies for V4 as well.
Could you provide more details on the issues related to perf and billing you mentioned.

**Comment by tbasallo** [comment]
If it's the recommendation should a ticket get created with the DevOps team about removing the step that removes the "WEBSITE_RUN_FROM_PACKAGE" app setting?

The storage cost is this one #1307

**Comment by balag0** [comment]
Thanks, regarding storage cost, I am not totally sure if the storage costs mentioned in the linked issue is completely due to run from package. There are other feature like logging that could be contributing as well. (Use app insights instead)
Internally every time a new worker is added for the app , the zip contents from storage account need to be downloaded. For short lived instances this could contribute to some billing impact so it really depends on the usage pattern. There is also a best effort local cache of the zip which can help avoid redownloading the zip on each new instance but this is not guaranteed all the time.

@patelchandni Could you please help take a look at the devops task and see if you notice anything.

**Comment by patelchandni** [comment]
@tbasallo Please clarify which deployment method is selected for the DevOps task? If "Zip Deploy" is selected, then WEBSITE_RUN_FROM_PACKAGE app setting will be removed. If "Run From Package" is selected, then WEBSITE_RUN_FROM_PACKAGE = 1 is added.

**Comment by tbasallo** [comment]
Zip deploy is selected. I thought I read zip deploy and run from package were recommended, which seems to be at odds. 

Which is the recommended deployment method?

**Comment by patelchandni** [comment]
@tbasallo the recommended deployment method is Run From Package.
