### ISSUE TITLE
Getting error on v4 function with Azure data factory. It works fine with Postman

### ISSUE THREAD

**Issue by ankku** [Azure/Azure-Functions#2139]
Function App name: afmodel
Tools used: Azure Data Factory
New V4 app or existing V3 app migrated to V4: new v4

I created an HTTP triggered function which works fine when called from POSTMAN but when called from inside Azure Data Factory by calling in Azure function Activity, I get error as below :

`2022-01-06T10:40:03.591 [Information] C# HTTP trigger function processed a request.
2022-01-06T10:40:03.640 [Error] Executed 'Function1' (Failed, Id=efff879e-e645-4327-8455-26a6741a8d1b, Duration=2ms)Specified method is not supported.
2022-01-06T10:40:45.876 [Information] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=f5ceb492-7fc3-4e6f-a562-cf96d0e9ae36)
2022-01-06T10:40:45.876 [Information] C# HTTP trigger function processed a request.
2022-01-06T10:40:45.912 [Error] Executed 'Function1' (Failed, Id=f5ceb492-7fc3-4e6f-a562-cf96d0e9ae36, Duration=2ms)Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
2022-01-06T10:42:41  No new trace in the past 1 min(s).`

The function take a json array as a body and when hardcoding the body and passing it in ADF, the function succeeds but it fails as body is coming from a lookup activity and it is inserted as @activity.lookup1.output.value. The error we get in ADF is 
`Failure type
User configuration issue
Details
Call to provided Azure function 'Function1' failed with status-'InternalServerError' and message - 'Invoking Azure function failed with HttpStatusCode - InternalServerError.'.`

More discussion with Microsoft Community on this issue can be found here. We are unable to figure out where the issue is

[https://docs.microsoft.com/en-us/answers/questions/684218/unexpected-error-on-passing-json-value-in-azure-da.html?childToView=684407#comment-684407]

**Comment by v-bbalaiagar** [comment]
Hi @ankku , I went through the logs for your function app. Function was running on 0 worker instance for more than 385 minutes between 1/7/2022 1:30:00 AM and 1/7/2022 8:00:00 AM. 

Function App was offline due to previous deployment. Please restart the Function site manually or redeploy the function site to get the issue mitigated or use the App Offline History detector to check if the function was offline during this period.
Please visit [Azure App Service Deploy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops) for more information.

Also, Your Function app is pinned to extension bundle version 2.8.3, but the latest version for v2 is version 2.8.4
For more information - https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-5.0

Please check and let us know if this helps.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
