### ISSUE TITLE
Improve portal support for AI key configured as KeyVault reference

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#2243]
Portal requires AI instrumentation key to query App Insights metrics.
When logged in user only has Reader level permissions, the key cannot be fetched and portal will not display the metrics.

If there is no other solution out of box solution provided by AI, we need an api that portal can use with reader level access that returns the AI key to handle this scenario.

**Comment by mattchenderson** [comment]
I only just became aware of this item and strongly disagree with the premise. If it's data in Key Vault, access needs to be controlled by Key Vault. We cannot expose it in the management plane for any reason.

Closing so as not to create question of if we are doing this. We will not.

**Comment by drdamour** [comment]
@mattchenderson i dont think thats what was being suggested, i understood this as defining a keyvault reference that as long as the apps managed identity is granted read could retrieve the value and query app insights with it.  that doesn;t violate the security in the way you are concerned i think

/harsh close

**Comment by Tbohunek** [comment]
How did Azure Key Vault got mixed in? This is Application Insights, and its instrumentation key is visible in the plain sight in properties of the AppInsights resource as well as in the Hidden Tag.
So Azure Portal could easily fetch it from AppInsights resource rather than from AppService Environment Variables, which indeed require extra permission and pose a security concern.

@balag0 I confirm it's not possible to view Insights from the AppService/Function, however if you go directly to the AppInsights resource, then you can view the "data" like graphs and logs even as a `Reader`.

**Comment by TroyWitthoeft** [comment]
Unfortunately, looks like the issue title proposed "KeyVault reference" which pulled KV (and it's independent IAM) into the discussion and muddied the waters.  All of this is relevant to the [two year old request](https://github.com/Azure/Azure-Functions/issues/1882) to allow folks to have access to the function monitor logs without granting them contributor rights.   Only contributors can see the monitor tab below.  Even if you have monitoring reader you will be unable to view logs.  I will be grayed out ... 

![image](https://github.com/Azure/Azure-Functions/assets/1102958/26c88571-e1c5-4b7c-9b7d-e670f412eb9b)
As of today, this feature request is still outstanding.
