### ISSUE TITLE
Consumption Plan - Service Bus Topic Trigger - Idle Function

### ISSUE THREAD

**Issue by napalm684** [Azure/Azure-Functions#229]
I have an azure function that is triggered via service bus topic messages.  It is running on the pricing tier consumption.  The problem I have is periodically the function stops executing and lets messages pile up in the service bus topic queue for my subscription.  I checked on the function app settings and the option to have it always on is hidden (I see it load on the page load then disappear).  Can you use the consumption plan and still have the function always on?  Otherwise, is there a way to keep the function alive as we don't know when messages come in but we want them to process as they arrive.  Something is not right as the azure function is not triggering on message arrival.  However, as soon as I visit the page to look at the function's code it wakes up and processes all the messages?

Are there any known issues on this flow?

**Comment by lindydonna** [comment]
Always On is not applicable when running on a Consumption plan. The "central listener" component **should** wake up the function when there are new messages, but due to the bug you referenced, it didn't work correctly previously. We'll find out if the fix is actually deployed.

For more info on the two plan types, see [Choose the correct service plan for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale)

**Comment by napalm684** [comment]
@lindydonna Thank you for responding we are in the midst of user acceptance testing and I have had to keep a browser tab open for the function to process messages arriving at the topic queue.

**Comment by lindydonna** [comment]
@napalm684 As an ugly hack, you could add a timer trigger that runs every minute and wakes up the Function App.

**Comment by napalm684** [comment]
@lindydonna I am considering this as a short term workaround as obviously that eats into the function execution grant that adds to the consumption plans appeal.  I am stuck at the moment waiting for data to come through to see if adding manage rights fixed the problem.

**Comment by lindydonna** [comment]
@napalm684 Agreed, I intended it as a short-term workaround. Manage rights should fix the problem.

**Comment by napalm684** [comment]
@lindydonna Ok now I am a bit concerned I got data and even with manage rights the function is still not being triggered.  Should I be using the root key instead of the one I created with manage, send, listen rights?

**Comment by lindydonna** [comment]
@napalm684 How did you deploy your functions?  Not all deployment options will synchronize triggers with the central listener. Click the Refresh button in the portal to ensure your triggers are registered.

**Comment by tohling** [comment]
@napalm684, could you kindly share your Fuction App name directly or indirectly?  If indirectly, kindly follow instructions here https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly

**Comment by napalm684** [comment]
@lindydonna FTP from our in-house Octopus deployment system.  I assume you are referring to the refresh button on the function app settings?  I did try start/stopping that for what it is worth I will try refresh.

@tohling Here is a dummy site in the same region and resource group: http://dummy123456.azurewebsites.net  the one you care about begins with an 'S'

**Comment by tohling** [comment]
@napalm684, thanks!

One more question, the connection string for your Service Bus, does it have the EntityPath segment at the end? If yes, please remove it as see if that helps.

If the above does not apply to your Function, that's alright.  I'll investigate and update this thread.

**Comment by napalm684** [comment]
@tohling no thank you I appreciate the guidance.  As for the connection string the entity path is removed the functions threw an error notification (toast) when viewing them in the azure editor when I had that initially.

**Comment by tohling** [comment]
@napalm684, I do see some anomalies in our logs.  I need some time to repro this.  I will get back to you within a day with an update on this thread.

**Comment by napalm684** [comment]
Thanks @tohling look forward to hearing what you find out!

**Comment by tohling** [comment]
@napalm684, if you have accessed the Azure Portal, that forcibly causes your Fuction App to come alive.  So, it may look like it's working because the runtime implementation is doing its job.  What I need to make sure is that after your Function App idles out at ~5mins, it will be still be "woken" up when new events are detected.

It may take me some time for me to repro the conditions.  In the meantime, is it possible for you to move the Functions that deal with the deadletterqueues to a different Function App? e.g.,  The 2 that are using the regular subscriptions can stay but migrate the Functions that are listening to the dead letter queues to a different Function App within your plan.  Let me know if you see a difference in behavior.

**Comment by napalm684** [comment]
@tohling It is possible I will have to talk with my team about that.  As for accessing my function via the portal I have not (I am simply watching on the kudu function log via the direct link to that log i.e.: https://<functionname>.scm.azurewebsites.net/azurejobs/#/functions) which yesterday did not wake up the function or anything.

Without having the function open it has been running all day the only tweak made last night before I went to bed was switching over to the RootSharedAccessKey?

**Comment by lindydonna** [comment]
I'm not sure if this is related to the issue, but note that FTP upload will not register triggers with the central listener. We need to update our documentation on this, but here's the GitHub issue that documents the behavior: https://github.com/Azure/Azure-Functions/issues/210

**Comment by tohling** [comment]
@napalm684, thanks for the clarification.  I wanted to see if I could unblock you, hence the recommendation to create the other Function App for your subscriptions listening on the dead letter queues.  Seems like things are working now base on the changes you made last night, so I am glad you are unblocked.  

Btw, per @lindydonna's comment above, is it possible that the issue is the cause?

I will investigate with a repro nonetheless and update this thread.

**Comment by napalm684** [comment]
@lindydonna certainly worth a shot and couldn't hurt to do this on deployment as a general practice.  I can add that as a step to our deployment definition.

@tohling Can you clarify was the theory the dead letter queue triggers caused the function to go to sleep?  As @lindydonna mentioned earlier the refresh click initially didn't do anything with the non-root access key.  Maybe it was a combination of both the key change to root and the refresh?

**Comment by tohling** [comment]
@napalm684, all your 4 Functions currently reside inside a single Function App.  That Function App is an instance of the process that gets launched to run the code in one or more of your Functions.  In Consumption Plan, the lifetime of the Function App hosting all your Functions is ~5 mins, after which, the Function App process is terminated.   

Typically, the Function App gets launched under 2 scenarios:

**Scenario 1. User accessed Function App in Azure Portal -** The UX loads the Function App on the user's behalf, forcibly launching the Function App process if no active instance exists.  

**Scenario 2. Function App is launched due to trigger -** Absent of _Scenario 1_, Azure Functions has an internal system that acts as a proxy listener to your Service Bus topic subscription.  If a new event arrives, and there are no active instances of your Function App, the internal system will launch a new instance of your Function App.  This internal system is also responsible for scaling out instances of your Function App to keep up with the incoming load.

Based on my observation of the logs last night, it seems that the internal system was only monitoring for events from your Functions that are not using the dead letter queues.  There may be 2 possible explanations:

1. When you made changes to the _function.json_ files, the sync did not occur correctly, as mentioned by @lindydonna above.

2. There is a bug in the internal system in which 2 functions with the same subscription but different path _({subscriptionName} vs. {subscriptionName}/$DeadLetterQueue_) cannot reside in the same Function App.   I will need to confirm this but if that's the case, then the recommended temporary workaround is to move the Functions that are using the dead-letter queues to their own Function App.

**Comment by napalm684** [comment]
@tohling thank you for the explanation please let me know if you are able to repro before I get approval from my team to move them to another function app.

**Comment by napalm684** [comment]
@lindydonna is there a URL that can be used to call this sync triggers endpoint?  The issue linked seems to utilize web deploy which we are not using.  I'd need a way to make a script or console app make the API call so it can be utilized in our Octopus deploy definition.

**Comment by lindydonna** [comment]
@napalm684 Yes, there's a Kudu API you can call either through ARM or directly.

See https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/FunctionsWebDeploy.json#L90

**Comment by napalm684** [comment]
This is what I am confused about that is the same link I was looking at that I thought was web deploy specific 

          "properties": {
            "synctriggersstatus": "[listsyncfunctiontriggerstatus(resourceId('Microsoft.Web/sites', parameters('siteName')), '2015-08-01').status]"

There doesn't seem to be a URL here also I am not sure I know what ARM is?

**Comment by lindydonna** [comment]
@napalm684 ARM is Azure Resource Manager. I'm looking up the Kudu API and I'll get you that shortly.

**Comment by napalm684** [comment]
Read about ARM we aren't using azure cli of powershell for deployment yet but I imagine we should at some point.  Not sure how this ties in with FTP though as you'd still need to upload the files after using the cli or powershell to create the function app right?  Sounds like the Kudu API call makes the most sense after upload via ftp.  Looks like I can use a small powershell call to the rest endpoint once it's identified.

**Comment by tohling** [comment]
@napalm684, I found the issue.  The internal system's (also known as the central listener) support for dead letter queues is currently broken.  Your Functions that rely on dead letter queues will not be triggered by the central listener.  

**Cause**
This is a regression due to a recent fix for another use-case. I have fixed this bug and will update this thread again when the fix is rolled out to production.  The ETA is 2-3rd week of April.

**Comment by napalm684** [comment]
@tohling Were those functions also the reason that non-deadletter functions weren't being triggered too?  If so does the advice stand that these functions should be broken out into their own function app to be triggered manually until the fix is deployed?

@lindydonna were you able to find the api endpoint for kudu to sync the triggers?  I did some digging of my own and was only able to find this in the context of the kudu arm client.
https://github.com/projectkudu/ARMClient/wiki/Functions-Apis

**Comment by tohling** [comment]
@napalm684, in your current setup with the 4 Functions inside the same Function App, after the Function App process has been terminated due to the 5 mins time out,  unless at least one of the 2 non-dead letter queue Functions have new events, the Function App will not be woken up even if there are new events in one or more of your dead letter queues.  

At first I thought it was only a dictionary indexing issue so I recommended that you move the 2 dead letter queue Functions to their own Functions App, but that is not the case.  The bug was more involved than that and moving them to their own Functions App will not help.

In the meantime, you may keep all 4 Functions in the same Function App but also add a 5th Function, specifically a Timer-Triggered Function that will forcibly make the Function App come alive every hour, 6 hours or once a day depending on the load in your dead letter queues.  This will make sure that even the 2 dead letter queue Functions get executed periodically if there are events for them.

**Comment by napalm684** [comment]
@tohling just to be clear this only affects the dead letter queues not the main queues which will wake up as desired?  I ask since it was the non-deadletter queues I originally saw backing up and not waking up the function app.  I am now wondering if that was due to the permission issue and not having the trigger sync run.  I think there were two issues here that one and the one you have identified with dead letter.

**Comment by tohling** [comment]
@napalm684, yes the bug only affects Functions that use dead letter queues.  You may be right in that the original observation was due to the missed sync.  In that case, just make sure that you always sync whenever you make changes to any of the Function configuration.

**Comment by lindydonna** [comment]
@napalm684 To call the syncTriggers endpoint manually, do a POST to https://function-name.scm.azurewebsites.net/api/functions/synctriggers. You need to be authenticated with the same user context as your Azure credentials.

**Comment by lindydonna** [comment]
@napalm684 Just saw you previous reply. You can indeed us ARMClient to sync triggers as mentioned here: https://github.com/projectkudu/ARMClient/wiki/Functions-Apis

Here's how to get ARMClient: https://github.com/projectkudu/ARMClient

**Comment by lindydonna** [comment]
@napalm684 Here's an even better approach:

https://github.com/davidebbo/AzureWebsitesSamples/blob/master/PowerShell/HelperFunctions.ps1#L360-L365

I'll make sure we add this to our documentation.

**Comment by napalm684** [comment]
@lindydonna does this require azure powershell (the last one you posted that is).  Looks like it based on the command name in that function?

**Comment by lindydonna** [comment]
@napalm684 Yes, it uses Azure Powershell.

**Comment by napalm684** [comment]
@tohling Hello just curious on the ETA for the fix since we are in the 2nd/3rd week of April now.  Thanks!

**Comment by tohling** [comment]
@napalm684, There was a delay in the deployment pipeline due to other non-related issues.  The fixed is being deployed right now.  Our deployment rolls out in batches.  I just checked and the new project ETA is 5.2.

**Comment by tohling** [comment]
@napalm684, the fix is deployed in production.  Your functions that trigger on deadletter queues should now work. When you get a chance, kindly retry and let us know you are unblocked on this issue.

**Comment by napalm684** [comment]
I have confirmed this indeed appears to be fixed.  Thank you @tohling and @lindydonna for all your assistance.
