### ISSUE TITLE
AZ Function Impersonation issues when deployed

### ISSUE THREAD

**Issue by EnmanuelParedesR** [Azure/Azure-Functions#2324]
Hello. 

# Work Case
Files on VM (On Azure) have to be uploaded to an AZ Blob Storage with some metadata. For this, I'm using an Azure Durable Function version 2.0 with .NET 6. 

# Issue  
I'm having issues while trying to impersonate my Azure Function so I can get access to a Shared Folder. Locally (with VPN) is working right, so is have to be some issues with networking, but I can't figure it out.

This is the code I use for the impersonation:

```C#
       [DllImport("advapi32.dll", SetLastError = true)]
        private static extern bool LogonUser(string lpszUsername,
           string lpszDomain, string lpszPassword,
           int dwLogonType, int dwLogonProvider, ref IntPtr phToken);

        [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
        private static extern bool CloseHandle(IntPtr handle);

        public static Result Impersonate<Result>(string domainName, string userName, string userPassword, Func<Result> actionToExecute)
        {
            IntPtr tokenHandle = IntPtr.Zero;

            int LOGON32_PROVIDER_DEFAULT = 0;
            //This parameter causes LogonUser to create a primary token.
            int LOGON32_LOGON_INTERACTIVE = 9;
            // Call LogonUser to obtain a handle to an access token.
            bool returnValue = LogonUser(userName, domainName, userPassword,
                LOGON32_LOGON_INTERACTIVE, LOGON32_PROVIDER_DEFAULT,
                ref tokenHandle);

//The rest is not needed.
}
```
I get a true front this, but when I execute a **Directory.GetFiles** with the server route I get:

```
"Access to the path '\\\\{IP}\\RepositorioDesarrollo\\PDFpublicador\\PublicadorDocumentos' is denied."
```

In the Azure Function, I can ping my VM (it's on Azure) with the VPN configured on it. 

---

I've been trying things around multiple posts, but I can't figure it out. I know this might not be the best use case for this, but it'll be awesome if I can get it done. 

Any suggestion?

**Comment by EnmanuelParedesR** [comment]
The VM is rejecting the request because the AZ Function IP range is not in a White List?

**Comment by bhagyshricompany** [comment]
Thanks for update can you you share the repro steps

**Comment by EnmanuelParedesR** [comment]
Hello, @bhagyshricompany thanks for the response. I'm going to check with the configuration over AAD, all the credentials and configuration are the same. 

I'm going to follow what you said, if anything I'll give you the repro steps.

**Comment by EnmanuelParedesR** [comment]
@bhagyshricompany, if I register the Azure Function as an App in the Azure AD, when I'm using the impersonate step:

```C#

 return WindowsIdentity.RunImpersonated(id.AccessToken, () =>
            {
                //string[] filePaths = Directory.GetFiles("\\\\{IP}\\RepositorioDesarrollo\\PDFpublicador\\PublicadorDocumentos", "*", SearchOption.TopDirectoryOnly)
                //                             .ToArray();
                return actionToExecute();
            });

```

I guess instead of using the user credentials and creating an access token (using advapi32.dll) I probably need to get an access token from the app and use it for the impersonation, right?

I already create the app register, but I'm waiting for the VM access and see if I can grant the app access to the folder.

Port 445 needs to be open, right? 

Thanks for the support!

**Comment by bhagyshricompany** [comment]
@EnmanuelParedesR  Yes, that is correct. If you register your Azure Function as an app in Azure AD, you will need to use the app's access token for impersonation instead of using user credentials.

When you create an app registration in Azure AD, you can configure the app's permissions and grant it access to specific resources, such as the folder that you mentioned. Once you have granted the app access to the folder, you can then use the app's access token to access the folder by calling the Azure AD token endpoint and passing the app's client ID and client secret as part of the request.

Regarding the port 445, Yes it needs to be open, because it's the default SMB port. SMB (Server Message Block) is a network protocol that allows shared access to files, printers, and serial ports between nodes on a network.

You should be able to configure the Azure function's app registration to have the permissions you need, and your function should be able to access the folder using the app's access token.

Just a reminder, you should be extra careful when using impersonation and ensure that you are only granting the app the minimal permissions it needs to access the resources.

**Comment by EnmanuelParedesR** [comment]
For folder access in the VM I just have to go into the machine -> Search the folder -> Permissions and search/add the Azure Function AD Id there, right? Because I try it and I can't see it... Sorry, I'm not an expert in that part so I don't know if I'm missing something. Btw, the folder right now has read permissions for "Everyone". 

- The impersonation with the AD Az Function Access Token is easy
- I'm trying to contact the VM admin for the port opening because if I try for example a 'net use' to the folder on azure it gives me an "Access is Forbidden" error.

**Comment by EnmanuelParedesR** [comment]
I'm closing the issue, I didn't get access to the VM on time so I end up using a Powershell for the upload. Thanks for the help, I'm really sure those points you mention should work.
