### ISSUE TITLE
Container-based function app lost costom appsettings after being recycled by `CORSSettingsChanged` and `AppSettingsChange`

### ISSUE THREAD

**Issue by blueskyson** [Azure/Azure-Functions#2327]
## My deployment steps
My project structure is like:
```
.
│  Dockerfile
└─src
    │  <<project name>>.sln
    │
    └─<<project directory>>
        │  .gitignore
        │  <<project name>>.csproj
        │  host.json
        │  local.settings.json
        │  Startup.cs
        ├─Functions
        │      SubscriptionExpiredTimerTrigger.cs  # Azure Function 1
        │      SubscriptionRenewTimerTrigger.cs    # Azure Function 2
        │
        ├─Properties
        │      launchSettings.json
        │
        ├─Services
        │  │  MyService.cs
        │  │  IMyService.cs
        │  │
        │  └─Models
        │          LoginParam.cs
        │
        └─Utils
            └─Appsetting
                    RootSetting.cs
```
I used the Dockerfile from the project to build a function app image:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

# Build requires 3.1 SDK
COPY --from=mcr.microsoft.com/dotnet/core/sdk:3.1 /usr/share/dotnet /usr/share/dotnet
COPY ./src/<<project directory>> /src/<<project directory>>
RUN cd /src/<<project directory>> && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice
FROM mcr.microsoft.com/azure-functions/dotnet:4
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    WEBSITES_ENABLE_APP_SERVICE_STORAGE=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```
I took a reference from [Linux-container-from-ACR-with-private-endpoint](https://azure.github.io/AppService/2021/07/03/Linux-container-from-ACR-with-private-endpoint.html#advanced-scenarios) and create an function app of App Service B1 (Linux) by Terraform. Then, I deploy a function app by the following Ansible playbook from a ubuntu 18.04 VM on azure:
```yaml
- name: Force Login using identity
  command: az login --identity

- name: Get function app identity's clientId
  command: az identity show --resource-group "{{ functionapp_resource_group }}" --name "{{ functionapp_user_identity }}" --query clientId --output tsv
  register: identity

- name: Config app settings
  command:
    az function app config appsettings set --name "{{ functionapp_name }}"
    --resource-group "{{ functionapp_resource_group }}" --settings "{{ item }}"
  with_items:
    - "WEBSITES_ENABLE_APP_SERVICE_STORAGE=false"
    - "SubscriptionExpiredSchedule=* 30 * * * *"
    - "KEY=VALUE..."

- name: Config properties
  command:
    az resource update --resource-group "{{ functionapp_resource_group }}" --name "{{ functionapp_name }}/config/web"
    --set "{{ item }}" --resource-type "Microsoft.Web/sites/config"
  with_items:
    - "properties.acrUserManagedIdentityID={{ identityId.stdout }}"
    - "properties.acrUseManagedIdentityCreds=true"

- name: Deploy the function app
  command:
    az function app config container set --name "{{ functionapp_name }}"
    --resource-group "{{ functionapp_resource_group }}"
    --docker-custom-image-name "{{ docker_registry_host }}/{{ image_name }}:{{ image_tag }}"
    --docker-registry-server-URL "{{ docker_registry_host }}"
```

## What happened
I noticed that the function app worked fine when it just had been deployed (2023-01-17T02:29:27.485Z). But after a while, it unexpectedly redeployed because of `Recycling container because of CORSSettingsChanged and CORSSettingsChanged = Microsoft.Web.Hosting.CorsSettings` (2023-01-17T02:37:22.159Z). See the following log from Deployment Center:

```
2023-01-17T02:29:27.044Z INFO - Pull Image successful, Time taken: 1 Minutes and 7 Seconds
2023-01-17T02:29:27.485Z INFO - Starting container for site
2023-01-17T02:29:27.485Z INFO - docker run -d --expose=80 --name <<functionapp name>>_0_4b241f6f -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=<<functionapp name>> -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=<<functionapp name>>.azurewebsites.net -e WEBSITE_INSTANCE_ID=5b6600aecfae7b5eb1290df18fcc42fb8bc88d7b721b9274087658bfa90a5d85 -e WEBSITE_USE_DIAGNOSTIC_SERVER=False <<my acr>>.azurecr.io/<<name>>:<<tag>>

2023-01-17T02:29:27.485Z INFO - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2023-01-17T02:29:29.726Z INFO - Initiating warmup request to container <<functionapp name>>_0_4b241f6f_msiProxy for site <<functionapp name>>
2023-01-17T02:29:29.874Z INFO - Container <<functionapp name>>_0_4b241f6f_msiProxy for site <<functionapp name>> initialized successfully and is ready to serve requests.
2023-01-17T02:29:29.874Z INFO - Initiating warmup request to container <<functionapp name>>_0_4b241f6f for site <<functionapp name>>
2023-01-17T02:29:39.659Z INFO - Container <<functionapp name>>_0_4b241f6f for site <<functionapp name>> initialized successfully and is ready to serve requests.
2023-01-17T02:37:22.159Z INFO - Recycling container because of CORSSettingsChanged and CORSSettingsChanged = Microsoft.Web.Hosting.CorsSettings
2023-01-17T02:37:28.816Z INFO - Pulling image: <<my acr>>.azurecr.io/<<name>>:<<tag>>
2023-01-17T02:37:29.124Z INFO - <<tag>> Pulling from <<name>>
2023-01-17T02:37:29.126Z INFO - Digest: sha256:49a690b289cd8a80d7104891a3ae5db38b8d6529f73b9b536c147d81a94a499e
2023-01-17T02:37:29.126Z INFO - Status: Image is up to date for <<my acr>>.azurecr.io/<<name>>:<<tag>>
2023-01-17T02:37:29.129Z INFO - Pull Image successful, Time taken: 0 Minutes and 0 Seconds
2023-01-17T02:37:29.188Z INFO - Starting container for site
2023-01-17T02:37:29.189Z INFO - docker run -d --expose=80 --name <<functionapp name>>_1_bf06fa66 -e WEBSITE_SITE_NAME=<<functionapp name>> -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=<<functionapp name>>.azurewebsites.net -e WEBSITE_INSTANCE_ID=5b6600aecfae7b5eb1290df18fcc42fb8bc88d7b721b9274087658bfa90a5d85 -e WEBSITE_USE_DIAGNOSTIC_SERVER=False <<my acr>>.azurecr.io/<<name>>:<<tag>>

2023-01-17T02:37:29.189Z INFO - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2023-01-17T02:37:31.739Z INFO - Initiating warmup request to container <<functionapp name>>_1_bf06fa66_msiProxy for site <<functionapp name>>
2023-01-17T02:37:31.819Z INFO - Container <<functionapp name>>_1_bf06fa66_msiProxy for site <<functionapp name>> initialized successfully and is ready to serve requests.
2023-01-17T02:37:31.820Z INFO - Initiating warmup request to container <<functionapp name>>_1_bf06fa66 for site <<functionapp name>>
2023-01-17T02:37:40.895Z INFO - Container <<functionapp name>>_1_bf06fa66 for site <<functionapp name>> initialized successfully and is ready to serve requests.
```
And the `~/LogFiles/Application/Functions/Host` from scm shows:
```
2023-01-17T02:52:54.786 [Information] Loading functions metadata
2023-01-17T02:52:54.804 [Information] Reading functions metadata
2023-01-17T02:52:54.805 [Information] 1 functions found
2023-01-17T02:52:54.812 [Information] 0 functions loaded
2023-01-17T02:52:54.826 [Information] Loading functions metadata
2023-01-17T02:52:54.832 [Information] Reading functions metadata
2023-01-17T02:52:54.833 [Information] 1 functions found
2023-01-17T02:52:54.834 [Information] 0 functions loaded
2023-01-17T02:52:56.016 [Information] Host Status: {
  "id": "<<function app name>>",
  "state": "Running",
  "version": "4.14.0.0",
  "versionDetails": "4.14.0+fc14864b4fc2a095f8cd92c7f0ca338dbeabd430",
  "platformVersion": "99.0.7.639",
  "instanceId": "5b6600aecfae7b5eb1290df18fcc42fb8bc88d7b721b9274087658bfa90a5d85",
  "computerName": "lw0sdlwk00033S",
  "processUptime": 926196,
  "functionAppContentEditingState": "Unknown",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "3.17.0"
  }
}
```

After this deployment, all of my custom configurations (e.g. SubscriptionExpiredSchedule=* 30 * * * *) in Azure Portal were lost:

![5Qgvc](https://user-images.githubusercontent.com/46962923/212867884-6b372915-9941-4ce6-b2a4-89c10ed0308c.png)

## What I guess and expect
Does anyone know how to prevent `Recycling container because of CORSSettingsChanged and CORSSettingsChanged = Microsoft.Web.Hosting.CorsSettings` from occurring again, so that my function app will only be deployed once? Besides, I found that `Recycling container because of AppSettingsChange and isMainSite = True` causes my custom configs lost as well.

I noticed that the redepolyment doesn't use `-e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false`. Is this issue related to this environment variable?

Also, I have a Networking setting to prevent any IP from connecting to this function app. Is this another potential cause?

--- update ---

The `CORSSettingsChanged` issue seems to be solved by setting up cors in my Terraform:
```tf
cors {
  allowed_origins = []
  support_credentials = false
}
```
But `AppSettingsChange and isMainSite = True` still let my function app down.

--- update ---

I found that it may relate to the "Reader" role of the storage account of the function app. When I change the role of the Ubuntu 18.04 VM to "Contributor", the recycling seems to disappear.

**Comment by bhagyshricompany** [comment]
thanks for update will check and update you soon

**Comment by bhagyshricompany** [comment]
The recycling of your function app container could be caused by several factors, including changes in CORS settings, app settings, and the access level of the storage account associated with the function app.

To prevent the recycling caused by CORS settings changes, you can set up CORS in your Terraform configuration as you mentioned, by specifying the allowed origins and support for credentials.

To prevent the recycling caused by AppSettingsChange, you can make sure that you are not making changes to the app settings during the deployment process. If you need to make changes to the app settings, you can use the Azure Functions app settings management API to update the settings without causing a recycling of the container.

Regarding the storage account, you are correct that the access level of the storage account can cause the recycling to occur. If you change the role of the Ubuntu 18.04 VM to "Contributor", it should prevent the recycling from happening as this role has higher level of access on the storage account.

Regarding the WEBSITES_ENABLE_APP_SERVICE_STORAGE env variable, it is used to enable or disable the use of the Azure App Service storage for your function app. If this variable is set to false, it should prevent the recycling caused by changes in the storage account.

Regarding the Networking setting to prevent IP connections, it is unlikely to be the cause of the recycling problem, as it only affects incoming connections to your function app and should not affect the internal behavior of the app.

**Comment by blueskyson** [comment]
Thanks for your quick and detailed explanation 👍.  I think this issue is resolved. Hope my function app will run perfectly without further trouble this week.

**Comment by blueskyson** [comment]
@bhagyshricompany Hi, I want to ask a further question. When the identity of my Ubuntu 18.04 VM only has "Reader" to the storage account of the azure function, why can I set appsettings successfully for the first time?

I guess there's a place to temporarily storge appsettings. After the container is recycled and reloaded, the temporary appsettings are flushed. Only when the user (or identity) that executed `az functionapp config appsettings` has "Contributor" role, it make a copy of appsettings to the storage. So, the functionapp can retrieve custom appsettings from storage after recycling. Does it make sense?

**Comment by bhagyshricompany** [comment]
@blueskyson t is likely that when you set the appsettings for the first time, the Azure CLI is using the temporary storage location for the appsettings. This temporary storage location is likely accessible to the identity with "Reader" role, which allows you to set the appsettings successfully.

When the container is recycled and reloaded, the function app needs to retrieve the appsettings from the storage account. If the identity that executed the "az functionapp config appsettings" command did not have the "Contributor" role, it would not have been able to copy the appsettings from the temporary storage to the storage account, and the function app would not be able to retrieve the appsettings after recycling.

It is possible that the Azure CLI is not outputting any warning or error message in this scenario, because it is designed to work with temporary storage locations and only copies the appsettings to the storage account when the identity has the necessary permissions. However, it is important to note that the appsettings will be lost when the container is recycled and reloaded in this case, if the appsettings were not copied to the storage account.

**Comment by blueskyson** [comment]
I found that even I manually set appsettings `FOO=BAR` on azure portal, that appsettings still disappeared after `Recycling container because of AppSettingsChange and isMainSite = True`. So the issue is not solved yet...

**Comment by bhagyshricompany** [comment]
It sounds like when you set CORS in your Terraform configuration, it allows your custom app settings to persist after recycling the container, whereas when you don't set CORS, your custom app settings are lost. This may be because the Azure portal's AppSettingsChange event, in combination with the setting isMainSite = True, is causing the custom app settings to be overridden. The "Contributor" role for your Ubuntu 18.04 VM should allow you to make changes to the appsettings, but it may not be sufficient to overcome the effects of the AppSettingsChange event.

**Comment by blueskyson** [comment]
OK, I'll build an environment and observe it for a while. I'll make some updates if I encounter another problem. Thanks.

**Comment by blueskyson** [comment]
Hi @bhagyshricompany unfortunately I encountered `Recycling container because of AppSettingsChange and isMainSite = True` with no reason in another deployment. Could you take a look if you have access to the Azure backend? The attached file is the Resource JSON.
[resource.txt](https://github.com/Azure/Azure-Functions/files/10532001/resource.txt)

**Comment by bhagyshricompany** [comment]
@blueskyson  will check and update soon.
Thanks

**Comment by blueskyson** [comment]
@bhagyshricompany Do you still investigate the az function resource? I'm going to delete it.

**Comment by bhagyshricompany** [comment]
will update checking on that

**Comment by blueskyson** [comment]
I found that not only container deployment has this problem, but this problem still occurs after I switch to zip deployment. So it might be related to the outdated Terraform version (v1.0.4), not Docker agent on Azure. Also, my function app uses dependency injection, but I think it's unlikely to have anything to do with it. Here's the Terrafrom script:
```tf
resource "azurerm_app_service_plan" "B1" {
  name                = "plan-B1"
  resource_group_name = azurerm_resource_group.mygroup.name
  location            = azurerm_resource_group.mygroup.location
  kind                = "Linux"
  reserved            = true
  sku {
    tier = "Basic"
    size = "B1"
  }
}

resource "azurerm_function_app" "myapp" {
  name                = format("myapp-%s", terraform.workspace)
  resource_group_name = azurerm_resource_group.mygroup.name
  location            = azurerm_resource_group.mygroup.location
  os_type = "linux"
  version = "~4"

  storage_account_name       = azurerm_storage_account.myapp.name
  storage_account_access_key = azurerm_storage_account.myapp.primary_access_key

  app_service_plan_id = azurerm_app_service_plan.B1.id

  identity {
    type = "SystemAssigned"
  }

  app_settings = {
    APPINSIGHTS_INSTRUMENTATIONKEY = "${azurerm_application_insights.myapp.instrumentation_key}"
    FUNCTIONS_WORKER_RUNTIME = "dotnet"
  }

  site_config {
    linux_fx_version = "dotnet|6"
    always_on = true
    cors {
      allowed_origins = []
      support_credentials = false
    }
  }
}
```

In Addition, I found there is a mechanism called *configuration drift*, which enforces the resources to keep the same states as in Terraform. Since our appsettings depend on the environments, we use Ansible to set up each appsetting that definitely change the states. I highly guess this is the root cause of this issue.
- reference 1: https://www.maxivanov.io/ignore-azure-functions-application-settings-change-in-terraform/
- reference 2: https://developer.hashicorp.com/terraform/tutorials/state/resource-drift

I also opened a topic in Terraform's forum: https://discuss.hashicorp.com/t/does-appsettings-disappearance-of-azure-function-relate-to-configuration-drift/50408

**Comment by bhagyshricompany** [comment]
@pragnagopa pls comment and validate the same

**Comment by blueskyson** [comment]
I solved it by adding `ignore_change` to Terraform script to allow changing app settings by Ansible. It works fine in recent weeks.
```terraform
lifecycle {
  ignore_changes = [
    app_settings # prevent TF reporting configuration drift after app code is deployed
  ]
}
```

**Comment by vinodazuredevops** [comment]
Hi Guys,

Did anyone got the resolution for the below problem.

Recycling container because of AzureStorageAccountsChange and isMainSite = True

Or development team is deploying the code and after sometime we see storage path is attached on the path mappings on configuration setting of app service, its very strange .

When I checked on the activity log of app service it showing an audit policy is triggered and then it updates the web site config .
Any help would be really appreciated .

Thanks,
Vinod J
