### ISSUE TITLE
BlobTrigger goes insane with billable transactions

### ISSUE THREAD

**Issue by mdddev** [Azure/Azure-Functions#2333]
Hello,

A while ago, my organisation rolled-out Azure Defender for Storage. Since then, the costs steadily increased. I now had a more in depth look at it and found out, that the 4-5 blob triggered functions in my premium-back plan went bananas. Please have a look a the metrics screenshot from the func host's storage account portal GUI (note, this storage account doesn't even host any blobs to trigger-on, I use a different storage account for this). I have not made any blob-specific changes to the host.json. The blob-triggers are executed 1x /day each.

As you can see, there were +1M billable transactions at some point (Defender for storage prices /10000 transactions). I refactored the blob-triggered functions to queue-triggered functions, with the queues beeing updated by an EventGrid subscription on new blob entries. As you can see the transactions drop to almost zero. And so is the cost of Defender. I am a bit shocked that a few blob triggers made such a cost difference.

Why is this the case? From now on I am really avoiding blob triggers. 

I am using the v4 runtime of Azure Functions on a Premium Windows Plan. The storage extension's version is 5.0.1.
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Blobs" Version="5.0.1" />

![image](https://user-images.githubusercontent.com/33447232/215484431-3cdce1f9-7e8c-4e74-98f9-85c32a50a64d.png)

**Comment by bhagyshricompany** [comment]
@mdddev thanks for the update  as per the plan you using is [v4 runtime of Azure Functions on a Premium Windows Plan. The storage extension's version is 5.0.1.]
The billing of Azure Functions on a Premium Windows Plan occurs based on the number of execution units used, the storage transactions, and the duration of function execution. In your case, with a Premium Windows Plan and v4 runtime, you are billed based on the number of execution units consumed and the duration of function execution.

For storage transactions, there is a set number of free transactions included in the Azure Functions pricing, and additional transactions are billed separately. When using a storage extension (in your case version 5.0.1), the number of storage transactions initiated by your functions will affect the overall cost. In your scenario, using blob triggers resulted in a high number of billable transactions, leading to increased costs.

Blob triggers in Azure Functions can be costly because they use high frequency storage transactions to initiate function execution. Each time a new blob is added to the storage account, it triggers the function, causing it to execute. This can result in a high number of billable transactions, especially if the number of blobs is large. In your case, with 4-5 blob triggers executing once per day, the number of billable transactions could have accumulated to 1 million, leading to high costs.

By refactoring your functions to be queue-triggered, you are able to reduce the number of transactions and hence the cost. Queue-triggered functions work by having an event (in your case, a new blob) added to a queue, and then the function executing when it processes the message in the queue. This method reduces the number of transactions and hence the cost, as there are fewer instances of function execution.

And can you share the function name region time eventid  info etc will check and update you soon.

**Comment by mdddev** [comment]
Thanks for the feedback. Unfortunately I cannot share all of this publicly. However, it was good that you confirmed that a blob-triggered functions indeed has the potential to cause excessive transactions. Though I don't consider 1x/day invocations (on new blob) as high frequency. It appears that the constant polling is to blame, especially if the blobs are kept in the container and not deleted after processing.

As you pointed out, some free allowance for storage transactions might apply and also the pure storage cost might not be _the_ issue for most. However, using blob-triggered Azure Functions in connection with Azure defender for storage is clearly to be avoided due to the sheet volume of transactions which are priced by defender by the 10000 lot. Maybe a warning would be suitable that using azure defender with services that use storage natively internally can lead to unexpected cost increases. At some time the % share of advanced threat protection cost attributable to that Azure Function storage account was well above 25%, and this for mainly doing nothing/just polling.

**Comment by bhagyshricompany** [comment]
Yes, you are correct. The constant polling of the blobs can lead to an increase in transactions and, as a result, an increase in costs when using Azure Defender for Storage. It's important to be aware of the potential cost impact and to monitor usage to ensure it doesn't get out of hand. A warning would indeed be suitable to inform users of the potential cost implications. It's always a good practice to be mindful of cost and usage when using cloud services.
if you are ok to share details in privately I can provide you a link.
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by bhagyshricompany** [comment]
No input /feedback hence closing this issue.
