### ISSUE TITLE
Concerns of FunctionsPreservedDependencies

### ISSUE THREAD

**Issue by SuyliuMS** [Azure/Azure-Functions#2349]
Hi, team,

We are going to use OpenTelemetry 1.4.0 in our function, but OpenTelemetry has a dependency to System.Diagnostics.DiagnosticSource and it will throw a exception when trigger functions:
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0

However we can add FunctionsPreservedDependencies element to .csproj file to fix this error:
```
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />
  </ItemGroup>
```

**Will System.Diagnostics.DiagnosticSource.dll in FunctionsPreservedDependencies affect function behaviors?**

We are basically wondering what would be the impact for preserving our own dependency version for dlls also used by the function host and if it’s ok to preserve the System.Diagnostics.DiagnosticSource. We are on dedicated plan and we don’t use AppInsight – all of our instrumentations are Geneva based.

**Comment by bhagyshricompany** [comment]
Preserving your own dependency version for DLLs used by the function host is generally not recommended, as it can cause conflicts and compatibility issues with other dependencies that the function host uses. In general, it is best to rely on the default dependencies that are provided by the Azure Functions runtime and to avoid preserving dependencies unless they are specifically required by your function.

Since you are using Geneva-based instrumentation and not using AppInsight, preserving the System.Diagnostics.DiagnosticSource.dll should not cause any issues. However, it is always a good idea to test your function thoroughly after making any changes to your dependencies.
