### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.CosmosDB 4.2.0 dynamic type support IReadOnlyCollection<dynamic> input

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/Azure-Functions#2354]
Hi,
I am using cosmos db trigger function v3 and it works fine with Document type

![image](https://user-images.githubusercontent.com/92055761/226990001-2d9976dd-cbea-4c06-8bd7-1e4da65eb23c.png)

When I migrated it to v4 along with Microsoft.Azure.WebJobs.Extensions.CosmosDB 4.2.0 , it doesn't support IReadOnlyCollection<dynamic> with dynamic type (Type is not known)

![image](https://user-images.githubusercontent.com/92055761/226990822-2407c0fa-a6fd-4a8a-bf40-3ef8060ec22a.png)

Is there any solution in v4 for anonymous types documents as we don't have Document type in v4?

**Comment by bhagyshricompany** [comment]
Hi @ranjeetkpGit  In Cosmos DB Trigger Function v4, instead of using Document type, you can use the JsonElement type to represent the Cosmos DB document as a JSON object.

To use JsonElement, you need to change the trigger function's input parameter type from IReadOnlyCollection<Document> to IReadOnlyList<JsonElement>. or you can create custom class

**Comment by ranjeetkpGit** [comment]
@bhagyshricompany Thanks for reply.

Seems it is developed on top of Newtonsoft.Json. It works with Newtonsoft's JObject but not with System.Text.Json classes like JsonElement, JsonDocument etc.

IReadOnlyList with JObject worked in my case.

**Comment by bhagyshricompany** [comment]
You are correct that Microsoft.Azure.WebJobs.Extensions.CosmosDB version 4.2.0 does use Newtonsoft.Json and not System.Text.Json.

If you are using Newtonsoft.Json, then you can work with dynamic documents using JObject as you mentioned. JObject is a type from Newtonsoft.Json that represents a JSON object as a dynamic dictionary.

If you need to work with anonymous types in your Cosmos DB documents, one option is to use IReadOnlyCollection<JObject> instead of IReadOnlyCollection<dynamic>. JObject is a type from Newtonsoft.Json that represents a JSON object as a dynamic dictionary, and it is supported by both Microsoft.Azure.Cosmos version 3.x and version 4.x.
