### ISSUE TITLE
How to prevent XSS Attack in azure function app (http trigger) Swagger endpoint level

### ISSUE THREAD

**Issue by raiajithkumarr** [Azure/Azure-Functions#2367]
Hi Team,
Please provide suggestion or sample to prevent XSS attack in azure function app in c#.

For example once we create sample application and try to access url including xss attack (it should prevent xss attack and load swagger ui properly)

http://localhost:7154/api/swagger/ui?configUrl=https://jumpy-floor.surge.sh/test.json

**Comment by bhagyshricompany** [comment]
Thanks for reaching out.
you can check with below option.
 prevent XSS attacks in an Azure Function App with an HTTP trigger:

Input Validation:
The first step to prevent XSS attacks is to validate all user input on the server-side. This can be done by checking the request body, headers, and query parameters for any potentially dangerous characters such as <, >, &, ", and '. You can also use regular expressions or a third-party library like the Microsoft AntiXSS library to sanitize user input. It's important to note that input validation alone is not enough to prevent XSS attacks, as an attacker could bypass the validation by encoding their input.

Output Encoding:
Output encoding is the process of converting any user input that is included in the response into a format that is safe to display in the browser. This is done to prevent the browser from interpreting the input as HTML or JavaScript code and executing any malicious scripts. You can use the HttpUtility.HtmlEncode method to encode any user input that is included in the response. It's important to note that output encoding should be done at the point where the response is generated, rather than at the point where it is displayed in the browser.

Content Security Policy (CSP):
A Content Security Policy (CSP) is a set of directives that can be used to restrict the types of content that can be loaded by the client's web browser. This can be used to prevent XSS attacks by blocking any scripts or other types of content that are not explicitly allowed. You can use the Content-Security-Policy header in the response to specify which types of content are allowed and which are blocked. For example, you could use the default-src 'self'; script-src 'self' directive to allow only scripts that are hosted on the same domain as the application.

It's also important to keep your Azure Function App and its dependencies up to date with the latest security patches and best practices.

**Comment by raiajithkumarr** [comment]
Here we are aiming to enable/load swagger endpoint at azure function app level, and that endpoint should be free from xss attack.

Earlier we had similar issue with azure web app but it got resolved after updating nuget version 

From: 
  PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.5.1"
  PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="5.5.1"

To:
    
PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0"
 PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="6.5.0"
 
 But in Azure function app still XSS Attack exist,  after updating  **Swashbuckle.AspNetCore** with latest version i.e. 6.5.0
     PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" 
     
     
    JFYI, I created sample httptrigger function and then I enabled swagger endpoint by using AzureExtensions.Swashbuckle this package after this if we run like below mentioned url
    http://localhost:7154/api/swagger/ui?configUrl=https://jumpy-floor.surge.com/test.json
    it should take you to home page of swagger instead any other operations.

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment and validate

**Comment by bhagyshricompany** [comment]
Use a Content Security Policy (CSP) header: Set a Content Security Policy header to further protect your application from XSS attacks. You can configure the CSP header in your Azure Function app's host.json file:
{
  "http": {
    "routePrefix": "",
    "extensions": {
      "swagger": {
        "enabled": true,
        "routePrefix": "api-docs",
        "title": "My API",
        "description": "API documentation"
      }
    },
    "contentSecurityPolicy": "default-src 'self'; style-src 'self' 'unsafe-inline';"
  }
}
 Try out this check if its working  .
