### ISSUE TITLE
Could not load file or assembly 'System.ComponentModel, after upgrading to .NET 8

### ISSUE THREAD

**Issue by doorman02** [Azure/Azure-Functions#2424]
Hi, after upgrading to .NET 8 I am getting the following error when starting up my Azure Functions app on MacOs. 

`Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. My.FunctionApp: Could not load file or assembly 'System.ComponentModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f43f50a33'. The system cannot find the file specified.
`

So I narrowed it down to this line when configuring EntityFramework 8 dbcontext.

```
builder.Services.AddDbContext<DataContext>(x => 
                x.UseSqlServer(MyConnectionString), ServiceLifetime.Transient);
```

any idea how to solve this issue?

Thanks

**Comment by ghost** [comment]
How did you end up solving this @doorman02 ? What did you see?

**Comment by carlos-bankbi** [comment]
Any news on this? I am also stuck there.

**Comment by doorman02** [comment]
hi, follow the migration guide for isolated mode https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8

**Comment by ghost** [comment]
@carlos-bankbi follow the migration guide. In short: In-process Azure Functions haven't been updated to use .NET 8 (and won't be updated for .NET 10 so might as well migrate now).

**Comment by jimiscott** [comment]
Having pulled out my hair for several hours, I found the solution delete bin and obj directories, restart VS.

(I should have arrived at this solution earlier, but it took a walk to the shops and back to buy a beer).

**Comment by VincentLZZhang** [comment]
In my case, it's related to FUNCTIONS_WORKER_RUNTIME, I have some Nuget packages, which is not compatible with Isolated mode, and I set  FUNCTIONS_WORKER_RUNTIME to "dotnet-isolated", so I received the same error.

I change FUNCTIONS_WORKER_RUNTIME to "dotnet", and the error goes away. 

Very likely your Function App is not ready for isolated worker model, which is why doorman02 recommends to read the Microsoft document on migration from in-proc to isolated worker mode. But you need to keep in mind, you have to migrate your own Nuget packages as well.

**Comment by bigstream** [comment]
> Having pulled out my hair for several hours, I found the solution delete bin and obj directories, restart VS.
> 
> (I should have arrived at this solution earlier, but it took a walk to the shops and back to buy a beer).

you saved my day

**Comment by ekanshgarg7021** [comment]
If it is an error in your local setup of In-Process, you need to add this in your local.settings.json:
**"FUNCTIONS_INPROC_NET8_ENABLED": "1"**

**Comment by ghost** [comment]
@ekanshgarg7021 legend, thank you
