### ISSUE TITLE
[Visual Studio] Publishing does not properly set $(Configuration) for MSDeployPublish

### ISSUE THREAD

**Issue by mattdrewitt** [Azure/Azure-Functions#249]
Since currently we are unable to template files, I have resorted to manually templating files.  While doing this I discovered that no mater what configuration you are using for your publish, it will always `Debug`
eg:
```
<UsingTask TaskName="TransformXml" AssemblyFile="$(VSToolsPath)\Web\Microsoft.Web.Publishing.Tasks.dll" />
<Target Name="TransformNugetConfig" BeforeTargets="MSDeployPublish">
  <TransformXml Source="nuget.$(Configuration).config"
                Transform="nuget.Base.config"
                Destination="nuget.config" />
</Target>
```
This will always point to `nuget.Debug.config` no matter your configuration.

**Comment by lindydonna** [comment]
This is because the project file assumes a content publish, where debug vs. release does not matter. We recommend that you instead use precompiled functions, as the current funproj format is being replaced. See https://aka.ms/precompiled-functions and https://blogs.msdn.microsoft.com/webdev/2017/04/14/azure-functions-tools-roadmap/

**Comment by lindydonna** [comment]
Closing as this is fixed in the new VS 2017 tools
