### ISSUE TITLE
Functions seems to be corrupting binary data

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#253]
Tried a slightly less complex use case with Functions tonight, got close, but still ended up having issues.

```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "dataType": "binary"
    },
    {
      "type": "blob",
      "name": "$return",
      "path": "files/new/response-{rand-guid}",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

```
module.exports = function (context, req) {

    context.done(null, req.body);
};
```

I get files written to storage, and the informaion looks *very close* to right.  but it's about 20% bigger and obviously at that point corrupted.  Any way I can just tell functions to pass the bytes along?  Is there something I need to call on `body` to thunk them back into real bytes?

**Comment by pragnagopa** [comment]
If you need to save a file as raw bytes, set the content-type request header to application/octet-stream. Let us know if you still see any issues

**Comment by atrauzzi** [comment]
I'll give it a shot shortly, stay tuned!

**Comment by army-watchfinder** [comment]
I've actually just done this in C#. 
Having the input in binary dataType is fine, but the output needs to be a byte array. My take on this is the following: 

functions.json:
`{
  "bindings": [
    {
      "authLevel": "anonymous",
      "name": "req",
      "methods": ["POST"],
      "type": "httpTrigger",
      "direction": "in",
      "dataType": "binary"
    },
    {
      "type": "blob",
      "name": "outputBlob",
      "path": "test-container/{rand-guid}",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
  ],
  "disabled": false
}`

The run.csx code is the following:

`public static void Run(HttpRequestMessage req, TraceWriter log, out byte[] outputBlob)
{
    // Get request body 
    var data = req.Content.ReadAsStreamAsync().Result;

    outputBlob = Helpers.ConvertStreamToByteArray(data);
}`

Hope this helps.

**Comment by fabiocav** [comment]
@army-watchfinder ; the `dataType` does not apply to C#/.NET functions. In that case, the type is determined by the parameters you're bound to. You can safely remove the `dataType` in your example with no change in behavior.

**Comment by army-watchfinder** [comment]
@fabiocav Thanks for that, I was actually under the impression I needed that, too. 👍

**Comment by nagendramishr** [comment]
I can confirm that **datatype** is needed for both python and node  for Blob input  where the blob is binary:
The issue needs to be reopend because there is no documentation that this is needed.

Functions version:  4.0.5530

Node:
    {
      "name": "myInputBlob",
      "type": "blob",
      **"dataType": "binary",**
      "path": "{queueTrigger}",
      "connection": "blobStorageConnectionSetting",
      "direction": "in"
    }

python:
@app.blob_input(arg_name="myInputBlob",
                path="{queueTrigger}", **dataType="binary",**
                connection="blobStorageConnectionSetting")


If dataType is not defined, the downloaded file is corrupt:

Should be:
0000000 211   P   N   G  \r  \n 032  \n  \0  \0  \0  \r   I   H   D   R
0000020  \0  \0  \b   q  \0  \0 002 020  \b 006  \0  \0  \0  \f 212   `
0000040   C  \0  \0  \0 001   s   R   G   B  \0 256 316 034 351  \0  \0
0000060  \0 004   g   A   M   A  \0  \0 261 217  \v 374   a 005  \0  \0
0000100  \0  \t   p   H   Y   s  \0  \0 026   %  \0  \0 026   % 001   I
...

but is actually corrupted as:
0000000 357 277 275   P   N   G  \r  \n 032  \n  \0  \0  \0  \r   I   H
0000020   D   R  \0  \0  \b   q  \0  \0 002 020  \b 006  \0  \0  \0  \f
0000040 357 277 275   `   C  \0  \0  \0 001   s   R   G   B  \0 357 277
0000060 275 357 277 275 034 357 277 275  \0  \0  \0 004   g   A   M   A
0000100  \0  \0 357 277 275 357 277 275  \v 357 277 275   a 005  \0  \0
0000120  \0  \t   p   H   Y   s  \0  \0 026   %  \0  \0 026   % 001   I
0000140   R   $ 357 277 275  \0  \0 357 277 275 357 277 275   I   D   A
...


This should be documented as its pretty normal to read binary blobs
