### ISSUE TITLE
Azure Functions Runtime configuration for created databases

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#272]
Because of some policy-based vpns, I can't run the the Functions within Azure, so I was really glad that the Runtime was released as an standalone product.

I'm trying to install AzureFunctionsRuntime on a VM running within Azure and after installation is successfull I tried to set everything up and chose to use a Azure Sql Database for the requested Database setup. It more or less works, so you can give it as servername the hostname of the Azure Sql Server and you can also setup user and password, even setting a prefix for the databasename is great, but as soon as I apply the settings, it fails with "there is already a database with that name".

I think this is nice for a lot of environments, where you don't want to pre create a database, but it fails for environments where you are just provided with an database pre-created.

So it would be nice, if the configuration-tool would just setup alle tables etc. when it realizes, that there is already a database and creates the database if it's not there.

**Comment by jvano** [comment]
We have plans to support Azure SQL Database and we will explore your suggestion of deploying to an existing database.

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

This version allows you to use SQL Azure. If you host the product in a Virtual Machine, make sure you have nested virtualization enabled since we use Hyper-V containers as a sandbox technology

If you want to host it within Azure, nested virtualization is supported in Azure Dv3 and Ev3 VM sizes:
https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/
https://azure.microsoft.com/en-us/blog/introducing-the-new-dv3-and-ev3-vm-sizes/
