### ISSUE TITLE
Azure Functions Runtime - PowerShell support?

### ISSUE THREAD

**Issue by OneCyrus** [Azure/Azure-Functions#288]
Is PowerShell support coming to Azure Functions Runtime at a later time? Or is it missing by design/limitations?

really looking forward to replace SMA with azure functions on-premise. C# and JavaScript support is already amazing. (just missing the http input trigger right now)

**Comment by ahmelsayed** [comment]
@jvano  I'd have thought it should just work, no?

**Comment by jvano** [comment]
For the preview, we only added templates for C# and javascript since the functions run inside a Hyper-V container and the container image is based on WinServerCore2016 and has not been fully tested with all languages but feel free to try PowerShell. 

The plan is to expose the same languages and capabilities at some point.

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we added support for:
- Functions v1 (.NET Framework) running in Windows Server Core container
- Functions v2 (.NET Standard) running in Windows Nano Server container

Now PowerShell templates are available in the Functions v1.
