### ISSUE TITLE
C#: document behavior of static classes that are loaded from a shared assembly

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#33]
It's possible to have static classes in a shared assembly, where multiple function invocations share this same loaded class.

@fabiocav Can you confirm the behavior that should be documented?

**Comment by fabiocav** [comment]
Although that is possible and it indeed works like that, I would discourage recommending this behavior to customers as this shared context is not guaranteed to be available (or the same) for every execution instance (due to scaling, restarts, **planned** future changes, etc.).

The recommendation should always be to have strive to have stateless functions and, when state is required, rely on an external cache (e.g. Redis, storage, etc.)

**Comment by lindydonna** [comment]
Thanks @fabiocav! In that case, what should we say about this in the documentation, if anything?  Other than the stateless function recommendation, that is.

**Comment by fabiocav** [comment]
I would avoid any information about sharing static context. The scenario is important, so we should have documentation on how to do this properly using Redis or Storage.

**Comment by lindydonna** [comment]
Closing this issue, thanks for the info!
