### ISSUE TITLE
Should I use SignalR or Azure Service Bus to buffer high load websites and the function backend?

### ISSUE THREAD

**Issue by makerofthings7** [Azure/Azure-Functions#346]
I want my mobile apps and asp.net website to leverage the same Azure function backend. 

When ASP.NET MVC or IIS do multithreading, there is a lot of overhead. What is the correct way to Async/await call an Azure function without negatively impacting IIS when under load? 

SignalR seems to have solved this problem. Does that mean that a SignalR component should exist between an ASP.Net website and a function? 

How would this compare to using async Service Bus as an intermediary between my website and Azure functions

**Comment by christopheranderson** [comment]
There is a couple of questions here and I generally think these kinds of questions would work better on Stack Overflow with some code samples.

With Azure Functions, always use async - while there is some overhead for a single call, it is way more efficient to use async/await.

SignalR is efficient because it is 1 persistent connection with many messages. This doesn't work in Functions because your Functions instances are very ephemeral and don't allow for this pattern to work for random clients.

Service Bus is a recommended approach because it allows for asynchronous messaging patterns (as opposed to HTTP which is often synchronous), which are very scalable. When you say Mobile App and ASP.NET MVC want to talk to Functions, does that mean you want the Mobile client and the Web server, but not the web client, or do you want the web client to talk to Functions as well? It's often the case that you don't want to give client access to your queue service (except many with a SAS token generated via an HTTP request). If it's a server you trust, queues make definite sense. The problem is responding to the client, since it'd have to listen on the queue in queue based approach (not really a common pattern for random clients).

One way of doing this would be an async http pattern which provides the best of both worlds.
clients (web + mobile + services) -> Http Function (returns 202 and correlation id) -> queue message -> queue function -> SQL/DocDB 
clients (web + mobile + services -> http function (returns result of the above queue function)

I think going forward, you should try asking any follow ups on Stack Overflow: https://stackoverflow.com/questions/tagged/azure-functions
