### ISSUE TITLE
Service Bus Topic trigger goes to sleep

### ISSUE THREAD

**Issue by madaz** [Azure/Azure-Functions#350]
I have a .Net 4.6 class library with 2 Service Bus Topic triggers for the same Service Bus, but different topics.

The Service Bus (Standard tier) and the Azure Functions (Consumption plan) are in the same Resource Group in 'Australia East'

When i visit the portal.azure.com site and navigate to the landing page for the specific Azure Function it all starts working.

Using Kudos DebugConsole i visited `D:\home\LogFiles\Application\Functions\function\{name}`  and there was no log details prior to time i visisted the portal azure function landing page.

Similar problem as discussed in #252

**Comment by JORGEGO** [comment]
Any advance?

**Comment by ahmelsayed** [comment]
This is by design. logs are not written to the file system unless the portal is pinging the app. This is an optimization because writing to the filesystem is slow and if you have a very high throughput function the file system will significantly reduce that. You should be logging into App Insights if you want high throughput logs. 

though if you don't care about that and always want log files set this flag in your `host.json`

```json
{
  "tracing": {
    "fileLoggingMode": "always"
  }
}
```

**Comment by madaz** [comment]
@ahmelsayed Did you fix the problem with Service Bus Trigger going to sleep for class libraries?  My issue is not with the logging, but thanks for the tip.

**Comment by ahmelsayed** [comment]
I should have read the whole issue and not just skim it :) 
Can you share your app name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by madaz** [comment]
@ahmedelnably 
```2017-07-07T02:15:17.927 Function started (Id=607e530a-38e5-4bdb-a9d8-63f4576926c9)```

**Comment by JORGEGO** [comment]
I have the same issue.

I remember the same behaviour to the Azure Web Jobs, its going to sleep if not activity is doing, and to maintenance the running status you should change the configuration and plan.

**Comment by tohling** [comment]
@JORGEGO, could you kindly provide the following?

1. In Portal, under the Log view, there should an entry that looks similar to the following, 

`2017-07-07T02:15:17.927 Function started (Id={some id})`

2. The region your Function App was deployed in.

We will investigate promptly.  Thanks!

**Comment by madaz** [comment]
@ahmelsayed Region is Australia East.

**Comment by ahmelsayed** [comment]
@madaz sorry for the delay. It appears that you have your service bus connection string with `accessRights: "listen"` we have a bug where we don't handle that correctly and incorrectly assume that there is no work to do. The fix is ready and will get deployed soon. a work around is to use a connection string with `manage` access rights. Would you mind giving that a try ?

**Comment by madaz** [comment]
@ahmelsayed thanks, I will try on Monday Australia AEST  when I'm back at work. How can we track when the listen fix is published.

**Comment by ahmelsayed** [comment]
I can update this issue once that's done if that works for you?

**Comment by madaz** [comment]
Yes please. Thanks

**Comment by Aravindhrk** [comment]
any updates on the fix?

**Comment by bwwilliam** [comment]
@christopheranderson I am wondering if you are aware of this issue. It is definitely a concern for my project. I am wondering if the CosmosDBTrigger has similar issue. We had to change to a webjob instead of using Functions CosmosDBTrigger.

**Comment by christopheranderson** [comment]
@tohling - Do you happen to know if we fixed this? It was scale controller it looks like from the issue text.

**Comment by tohling** [comment]
@christopheranderson, ScaleController has supported both `listen` and `manage` rights since end of July 2017 (see https://github.com/Azure/azure-webjobs-sdk-script/issues/1048)

@bwwilliam, are you experiencing issues with your ServiceBusTrigger? If yes, kindly open a new issue and provide us details about your Function execution directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately).  We will need the following:

1. Function App Name
2. Region
3. Function Name
4. Time range when issue(s) occured.

We will investigate promptly.  Thanks!

**Comment by bwwilliam** [comment]
Thanks for your reply @tohling , unfortunately, yes, we are having intermittent issue with ServiceBusTrigger.
I will get one of my colleages to open a new issue today with some details and tag you on that.

**Comment by mathewc** [comment]
The ScaleController issue has been resolved long ago (related to AccessRights).
