### ISSUE TITLE
Is there a limit to the deployment size?

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#364]
If I'm deploying a function over FTP, is there a limit to how large the function directory can be (including modules etc.)

**Comment by lindydonna** [comment]
@apengwin No, there's no limit. However, you'll be paying more Azure Storage costs, because the files are stored in Azure Files.

Note that on the consumption plan, triggers will not be synced to the scale controller if you use FTP. To work around, you should click the refresh button in the portal after your FTP upload. For more information, see https://github.com/Azure/Azure-Functions/issues/210
