### ISSUE TITLE
[App Insights]Is that possible to set AI request.resultCode within C# EventHubTrigger

### ISSUE THREAD

**Issue by erich-wang** [Azure/Azure-Functions#398]
[App Insights(Preview)](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)) provides a convenient way to enable App Insights within Azure Function which is great, I'm wondering whether we could explicitly set request.resultCode within Azure Function?

**Comment by TheeJamesLee** [comment]
Hi, from what I've found, the request logging to AI is done within the webjob.sdk internally with no easy way to manually override the values.

A discussion around the larger correlation story and integration with AI is happening on #245 .

In code [Here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs#L200) is where they are setting the result code to 0, as I've only just noticed - I had assumed they were doing 200 or 500 if an exception for all triggers except httpTrigger (where they use the response code correctly [shown here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs#L256) ).

I've just raised that as an explicit issue and linked that as well to the correlation issue. Azure/azure-webjobs-sdk#1236

------

If you need a work around, you'll need to not use the SDK included AI ability and just include you're own TelemetryClient (use a different webapp setting name for the instrumentation key) - [like how they are currently applying custom telemtry](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)#custom-telemetry) in the docs and send your own request data - however I am suggesting to move away from that pattern here Azure/Azure-Functions#390

**Comment by christopheranderson** [comment]
This is probably included in the scope of what you suggested, @TheeJamesLee. Would you be interested in making sure this is covered in your issue then we close this as a dupe?

**Comment by TheeJamesLee** [comment]
@christopheranderson  I have consolidated 'my' comments into #390 .

@erich-wang , can you just feedback if you feel your issue has been covered?

**Comment by erich-wang** [comment]
Thank you for the quick response. The reason I raised the question is it would be great if we could define our own logic for result of request.success/resultCode. (Currently the only way to set request.success as false is to throw an exception, I thought exception is kind of heavy). Just FYI, is it possible to provide the third optional parameter context (dictionary?) in Azure Function for such kind of override?

**Comment by TheeJamesLee** [comment]
> is it possible to provide the third optional parameter context (dictionary?) in Azure Function for such kind of override?

I think because the output is logging-esk that putting just properties into the generic context may not be the way to go (as a developer I now need to remember string keys... great :( more chances to make mistakes and harder adoption... ).  I will note those 2 points (setting success & resultCode) from your last message in the issue referenced above so that they stay captured.  

**I still think the workaround in my first reply is going to be your best option in the short term because you can manually define everything how you wish.**

Maybe just wrap it in a class library with a method signature of your choosing if you have a lot of functions, etc - that would be my approach but at the second I don't 'need' to push out custom metrics from the function.... yet... when i do, that's my plan.

@christopheranderson & @erich-wang I think this can be closed as we're covering everything in #390 .  @erich-wang the bigger discussion around working with AI as an output, etc is on #390 so have a quick read and join over there.

Regarding Exception is the only way to set 'false'... I personally think that is fine.  If the function did not correctly run, success == false, exception is outputted and very visible. If the function ran ... but your logic means it is bad,  resultCode == 400 (bad data, check incoming trigger data), 500 == , well internal server error ... an exception should have been thrown.

However, it is likely not everyone in their stacks are using the 2 properties with those exact codes, so yes a way to override is likely to be necessary... note, override, not required (and should be logically done internally because people will forget to set it).

**Comment by erich-wang** [comment]
Thank you for the detail explanation, I'm fine to close the issue.
