### ISSUE TITLE
Add VSTS info to CI article or link out to App Service CI article

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#46]
https://azure.microsoft.com/en-us/documentation/articles/functions-continuous-deployment/

**Comment by iamthemovie** [comment]
Is there a way of setting up deployment from VSTS in VSTS rather than manually setting it up through the Azure Portal?

We're looking for a way of deploying Functions via ARM templates then deploying the code to it through our CI/CD pipelines which are running through VSTS. 

Can we deploy Azure Functions through Web Deploy?

**Comment by lorenpaulsen** [comment]
Yes, the App Service Deploy step can be used to deploy the Function. As for configuring it through ARM, this is possible as well. Please see: http://case.schollaart.net/2016/10/20/deploy-your-azure-fuctions-using-visual-studio-team-services.html

**Comment by jeffhollan** [comment]
Tracking in docs repo
