### ISSUE TITLE
[Visual Studio] Can no longer name functions in New Function dialog

### ISSUE THREAD

**Issue by justcla** [Azure/Azure-Functions#492]
User (Ben Edwards) raised issue on [Marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools#review-details):

> Add a new httptrigger function, default name, anonymous access.
> 
> * Can no longer name functions, they now share the name of the function app that is created. Personally, I feel that this is how it should have always been, but now we are stuck with naming the class and the functionName attribute :/

Applies to extension version: 15.0.30901.0

**Comment by justcla** [comment]
Ben, can you please clarify the comment above?

When you say:
> they now share the name of the function app
what do you mean?
The new behavior is to choose a filename, in the New Item dialog.
We then set the class name and FunctionName attribute to be the same as the filename (without the .cs prefix).

And when you said:
> now we are stuck with naming the class and the functionName attribute
What did you mean?
Do you mean that, since we don't provide the ability to choose a FunctionName or class name during the New Function dialog, you must manually change the name after the class has been created?
Or did you mean something else?

Thanks for your input.

**Comment by elexisvenator** [comment]
Some clarification:

First, what has changed is in the New Item > Function App dialog there used to be a field to specify what the name of the new function was going to be. This field was then used to fill in the name argument of the FunctionNameAttribute that is on the newly created function.

Now, that field is gone from the dialog, and instead the name argument has the same name as the class/file that is created (in screenshot below that would be "Function2").

![image](https://user-images.githubusercontent.com/2984373/30253828-4e52dba6-96d0-11e7-94b7-e148154d86d4.png)

The intention appears to be to encourage 1 function per class with more consistent naming. I have to ask though why wasn't this the case from the start? This awkward double naming (class and attribute) feels like something that could have been avoided, but is very hard now due to backwards compatibility.

Overall I wouldn't consider this a bug, more a confusion on what the correct convention for defining functions is meant to be.

**Comment by alexkarcher-msft** [comment]
You're totally correct, in that the name should be both the class, and the function within. In VS you have full control over the name of the class in the previous screen in your example.
