### ISSUE TITLE
Azure iothub not triggering multiple Azure functions

### ISSUE THREAD

**Issue by aymanhendawy** [Azure/Azure-Functions#537]
I have azure-iot-hub Spectraqual-free.azure-devices.net triggering a function-app https://spectralqual.azurewebsites.net -consumption plan- as event hub triggers its functions, and have bindings with azure-table-storage https://spectralqualstorage.table.core.windows.net/ The problem is that the functions not work smoothly, something goes wrong, from the functions log I can see that some of my functions triggered but didn't receive eventhubmessage and accordingly not updating the bind table storage, others not triggered at all after it was triggered successfully before,

I developed those functions first with Visual studio code, after debugging and make sure it's free of error, I pushed them to the cloud using github sync, functions that was working -triggered- before on visual studio code, I can't make it triggered again on VScode, and I'm sure that iot-hub is receiving my messages, so the messages are delivered but no trigger happen, any help please!

**Comment by tohling** [comment]
@aymanhendawy, looks like you deleted your Function App.  I checked our logs and the last recorded activity was at logged   2017-10-09 12:26:38.4721562 UTC.  If you recreate the Function App and the issue reproes, kindly open a new issue so that we can investigate further.

Btw, I noticed that you have 5 Functions bundled together inside the same Function App.  These Functions are hosted inside the same Function App process and therefore share resources.  One of your function named **Events_Raw_Data_Report_Fn_App** seems to take an avg of >1-2 minutes to complete.  I don't have context on the resource usage for your Functions, but wanted to note that if the other Functions are triggered relatively at the same time, their perf may be affected by resource contention (if any) as well.
