### ISSUE TITLE
Azure Function Eventhub Trigger is continously receiving empty messages 

### ISSUE THREAD

**Issue by Kapster17** [Azure/Azure-Functions#589]
Azure event hub is receiving empty messages constantly. I checked all my publishes and am sure I am not publishing them. How do I know where are the message being published from ? I have a azure function trigger that prints nothing. C# Event Hub trigger function processed a message:

Even tried creating a new hub. This issue exists

EventHubTrigger-Shadow (, , cca2b799-b2c9- ...) |   | a minute ago | (0 ms) |  
-- | -- | -- | -- | --
EventHubTrigger-Shadow (, , 22ee5396-4366- ...) |   | 3 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 36291c1b-6068- ...) |   | 5 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , a6d1e881-0c73- ...) |   | 7 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , b231e89c-169b- ...) |   | 9 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 717364a8-5e10- ...) |   | 11 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , eaa094f7-7373- ...) |   | 13 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , c22987f0-7977- ...) |   | 15 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , dc2cf579-2ead- ...) |   | 17 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 4018f242-46d6- ...) |   | 19 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , e5355f06-ac82- ...) |   | 21 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 0f535e0d-9c50- ...) |   | 23 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 5eecab47-9e4e- ...) |   | 25 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , ba922374-0c3e- ...) |   | 27 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , ae2b6f9a-1162- ...) |   | 29 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 8fe792c0-1c76- ...) |   | 31 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , bad1f28f-0b01- ...) |   | 33 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 2b26a80b-d063- ...) |   | 35 minutes ago | (0 ms)

**Comment by tohling** [comment]
Your Function will only be triggered when there is at least 1 unprocessed message in the consumer group associated with your Function ($Default consumer is used if none is specified).  Are you sure that the EventHub consumer group associated with your Function has no unprocessed messages in them?

**Comment by Kapster17** [comment]
Yes. Very sure there are none. The messages are empty. Where do these empty message get generated ?

**Comment by tohling** [comment]
Not sure. I need to take a look at your EventHub.  Could you provide the following:

1. Visit the Azure Portal and open the Logs view for your Function or access the logs for your Function App.  If there are recent active executions, you should be able to see entries that look like the following:

2017-11-15T19:17:52.212 Function completed (Success, Id=**{some Guid}**, Duration=669ms)

I need the Guid.

2. The region in which your Function App was deployed in.

**Comment by Kapster17** [comment]
1) _context  a58acd04-5d16-4536-b80a-f59870694d69 
2) US West

**Comment by tohling** [comment]
Your Function named `AlarmEventHubTrigger `and `EventHubTrigger-Shadow` are both set to trigger on the event hub named odxel-eventhub-alarm with the same $Default consumer group.  There are messages in this eventhub/consumer group combination, but the message is being processed by the AlarmEventHubTrigger Function.  However, because EventHubTrigger-Shadow is also configured to retrieve from the same source, it gets triggered but upon retrieval, there are no messages to process.  

It does not sound like that was your intent.  I recommend assigning the correct event hub/consumer group to either one of the Functions and that should fix the issue.

**Comment by Kapster17** [comment]
Well, I did have EventHubTrigger-Shadow disabled when I had this issue. So there is only one function listening on the $Defaultconsumer group. 
Let me watch this again and will report as soon as I find it happening again,

**Comment by Kapster17** [comment]
Just noticed another one 3 hours ago (6:30 UTC )
4704dd04-78d1-4095-9afe-ab13f6c5b000

Both the function enabled with different consumer groups
AlarmEventHubTrigger - $Default
EventHubTrigger-Shadow - monitorl0cal

**Comment by tohling** [comment]
Thank you for updating the consumer group configuration for the `EventHubTrigger-Shadow` function so promptly.  I checked our log entries for the past day and here are some observations:

1. You updated your configuration such that `AlarmEventHubTrigger `is listening on `$Default` consumer group and `EventHubTrigger-Shadow` is listening on `monitorl0cal` consumer group of the event hub named `odxel-eventhub-alarm` at `2017-11-16 17:04:54 UTC`

2. Assuming that there were no previous/external retrievers for the `monitorl0cal` consumer group, your `EventHubTrigger-Shadow` Function should have started processing a backlog of events from the `monitorl0cal` consumer group around that `2017-11-16 17:04:54 UTC`.   I checked the Function logs for `EventHubTrigger-Shadow` during that time and can see that your Function was triggered and was processing large batches of events at a time.  If our assumption holds, then this is the correct behavior since `monitorl0cal` had no previous retrievers and now has to read the backlog of unprocessed events.

3. At around `2017-11-16 17:04:56.5925777 UTC`, your `EventHubTrigger-Shadow` Function seems to have caught up with processing the backlog of events from the `monitorl0cal` consumer group.  Around this time, the 
`AlarmEventHubTrigger` Function also starting processing events, which indicates that at least one new event is added to your eventhub, which translates to new events arriving for both consumer groups and both Functions will be triggered.  

4. At around `2017-11-16 17:04:56.6044373 UTC`, both `AlarmEventHubTrigger` and  `EventHubTrigger-Shadow` Functions started processing events at an interval of ~5 seconds.  

I have these follow-up questions:

1. Kindly let me know if the above observation is consistent with the in-flow of events into your event hub named `odxel-eventhub-alarm`

2. After the `EventHubTrigger-Shadow` Function has caught up with processing the backlog of events from the `monitorl0cal` consumer group in Step 3 above, it should have started processing the new events entering the event hub at roughly the same rate as the `AlarmEventHubTrigger` Function.  In your original post, you mentioned that while the `EventHubTrigger-Shadow` Function is being triggered, the events it receives are empty.  

With this updated setup, could you kindly let me know if 

a. Both Functions managed to retrieve copies of these new events, or 
b. Both Functions are executing but retrieving empty/null events, or
c. You are still seeing the new events in one but not the other, and if so, which one is retrieving empty/null events

**Comment by Kapster17** [comment]
Yes your observations are correct. 
My only concern here are the empty/null events.....Where do these get created ? 
Initially I had only one azure function listening to $Default consumer group. When I started seeing errors in the log that's when I created the shadow function...the default c# Event Hub Trigger to check what was the string being passed. The shadow function started showing me empty messages
C# Event Hub trigger function processed a message: 

What we need to figure out is the empty events ....whats the source and is it a bug in the EventHub.

**Comment by tohling** [comment]
Unfortunately, I was not able to repro the issue.  I created a Function App with 2 Functions listening to the same eventhub but different consumer groups:

1. FunctionA listening on consumer group **$Default**
2. FunctionB listening on consumer group **test**

And they are both picking up messages independently as expected.  

Could you kindly reach out to the EventHub team to see if they can help troubleshoot?  I was able to locate their GitHub repo: https://github.com/Azure/azure-event-hubs but you may have other avenues of contacting them.

**Comment by jeffhollan** [comment]
@Kapster17 following up on this to see if we can close. Did you get this to work? Let us know if anything we should be tracking and what you learned from support given referenced issue above.

**Comment by Kapster17** [comment]
I am working with your support team on  this issue. You can close this.
