### ISSUE TITLE
NET Standard Conversion Build Issue

### ISSUE THREAD

**Issue by hershize** [Azure/Azure-Functions#593]
# Objective #
I am working on converting my functions over from net461 to netstandard2.0. Currently running Windows 10 and Visual Studio v15.4.4.

# Problem #
I am getting a build error of the following:
![image](https://user-images.githubusercontent.com/12899565/32863588-a1a7eca4-ca21-11e7-9f43-8414b656c6d4.png)

Looking specifically at this `...Build.targets` file and line:
![image](https://user-images.githubusercontent.com/12899565/32863662-df053f70-ca21-11e7-8894-f9ddf7d7187d.png)

Here is my csproj file:
![image](https://user-images.githubusercontent.com/12899565/32863772-3e08a250-ca22-11e7-8838-94ef6aea9267.png)

# What I've Tried #
- Updating my Visual Studio to v15.4.4
- Deleting my global .nuget folder and rebuilding the project
- Converting the project to target `netcoreapp2.0`
- Closing Visual Studio and running `dotnet build` and `dotnet publish` command in the command prompt

Can anyone assist?

**Comment by jeffhollan** [comment]
I think the build is failing due to some dependency mis-match. For example the version of ServiceBus you have is expecting v2.1.0-beta4 and you have here 3.0.0-beta3.  Each of the binding extensions need to be versioned - in fact ServiceBus hasn't yet been ported over to netstandard2.0 so won't be able to upgrade until that happens if using the binding extensions.  Hopefully that helps.

**Comment by hershize** [comment]
That's right, I didn't see that ServiceBus is not ported over to netstandard2.0 yet. So there's no way for me to go to netstandard2.0 as of yet? When do you expect for it to converted? Btw, do you know when the binding redirect issue will be resolved?

**Comment by jeffhollan** [comment]
Should be there now - https://github.com/Azure/azure-webjobs-sdk/issues/1329 since last comment

Also binding redirect is being tracked here - https://github.com/Azure/azure-webjobs-sdk-script/issues/992

Believe we have some docs going out sometime this month to help detail current state and future thoughts. Definitely an issue we could use details on.  Would be great if you could share some of the scenarios/packages you are seeing conflicts with to help us target right fixes as well - as @fabiocav mentions in that issue it's not necessarily a cut-and-dry request.
