### ISSUE TITLE
Mocking databases in Functions

### ISSUE THREAD

**Issue by amusse** [Azure/Azure-Functions#609]
In my function, I am connecting to cosmos db and performing database operations. Is there anyway to mock those database operations by passing in a mock database for unit testing? The are currently only two parameters available (string message and ILogger for ServiceBusTopicTrigger) in the Run method.

**Comment by paulbatum** [comment]
Functions doesn't have anything built in for mocking. The way I've seen this done is that you put the logic you want to test into a class library and you test that with mocks however you desire. Then the actual functions simply call into your class library. However there can be some friction with this approach due to azure functions not having first class support for dependency injection (yet).

**Comment by amusse** [comment]
Is there an ETA of when dependency injection will be supported by azure functions?

**Comment by paulbatum** [comment]
We are making some progress but it is still months away. Right now the main work item is about getting DI working well for us internally which is tracked here:
https://github.com/Azure/azure-webjobs-sdk/issues/1206

There's still more work to do beyond that work item to get DI working well for customer use cases. I don't have an ETA right now.

**Comment by fabiocav** [comment]
Update on open issue. A lot of the DI features have been added to Azure Functions 2.0, with function level support for service injection being tracked by https://github.com/Azure/azure-functions-host/issues/3736
