### ISSUE TITLE
Discover HttpTrigger Functions from Logic App does not work with custom routes

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/Azure-Functions#621]
I wrote some functions invoked from a Logic App. I've notices that `HttpTrigger` functions does not show up in the Logic App Action selector if they use a custom route.

This function will show up in Logic App:

```csharp
[FunctionName("HttpTriggerCSharp")]
public static async Task<HttpResponseMessage> Run(
[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, 
TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");
}
```

This function ill not show up in Logic App

```csharp
FunctionName("HttpTriggerCSharp")]
public static async Task<HttpResponseMessage> Run(
[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "products/{id:int?}")]HttpRequestMessage req, int? id,
TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");
}
```

**Comment by patricklee2** [comment]
@CrazyTuna I'm unable to reproduce the problem
Can you provide more details about the functions and the logic app?

**Comment by jeffhollan** [comment]
Yes sorry this is by design. As Functions with routes as the way the Azure Function is invoked from Logic Apps is via calling an API "list invoke URL."  That URL will look something like `https://function.azurewebsites.net/api/my/{custom}/route?code=123` and Logic App doesn't have a way to parse the route template.  In other words we don't know what is static, and what should be replaced, and don't have a way to "replace" that with the native action.

You can get around it by providing an OpenAPI definition for the function and we will render the card based on the path parameters specified in swagger. Can also not use route if need to show in Logic Apps.

**Comment by CrazyTuna** [comment]
@jeffhollan Thanks. I am gonna try the OpenAPI and close the issue.
