### ISSUE TITLE
Bug? No-description warning in Microsoft.NET.Sdk.Functions.Build.targets

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#634]
VS2017 15.5.2, all latest fixes etc ... this is a Functions v1 project with the default SDK 1.0.6. While trying to figure out a different problem, I happened to notice a strange warning in my Error List which has no description, pointing to Microsoft.NET.Sdk.Functions.Build.targets. You can see from the screenshot that it doesn't like _something_ about the `<GenerateFunctions>` node... but what?

![fail](https://i.imgur.com/pLbBP5g.jpg)

**Comment by andreasbotsikas** [comment]
Same happens in SDK 1.0.7. There is a 
```
this.Log.LogWarning(end1, Array.Empty<object>());
```
in the MSBuild dll that outputs the process.StandardOutput.ReadToEnd()

**Comment by armadillomx** [comment]
I'm getting the same warning at line 32 with no description

**Comment by trbngr** [comment]
Same here. With a little digging, I was able to make it work for .NET Core.

Add this to your `.csproj`: 

```
  <Target Name="GenFunctionJsonFiles" AfterTargets="Build">
    <Exec Command="dotnet $(_FunctionsTasksDir)Microsoft.NET.Sdk.Functions.Generator.dll $(TargetPath) $(OutputPath)" />
  </Target>
```

**Comment by cschwendtner** [comment]
Seems to be the same reason as in Azure/azure-functions-vs-build-sdk#149.

The output of the generator process is logged, even when empty - as already mentioned by @andreasbotsikas
https://github.com/Azure/azure-functions-vs-build-sdk/blob/7c4ddc352cee340272bc356c1823b8fa7968f90e/src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs#L65

The, already merged, pull request Azure/azure-functions-vs-build-sdk#152 should fix this. So I think this issue can be closed.

It should be safe to ignore the empty warning, because there is no "real warning" behind it.
