### ISSUE TITLE
Documentation on the V2 runtime 

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/Azure-Functions#640]
Documentation on what feature come with the V2 runtime and the differences between the new templates.

V2 template
```
[FunctionName('Function1')]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Function, 'get', 'post', Route = null)]HttpRequest req, TraceWriter log)
        {
```

V1 template
```
[FunctionName('Function1')]
        public static async Task<HttpResponseMessage> Run(
            [HttpTrigger(AuthorizationLevel.Function, 'post', Route = null)]
            HttpRequestMessage req,
            TraceWriter log)

```

**Comment by pragnagopa** [comment]
Can you be more specific? Are you looking for documentation on V2 tooling? Or S[upported features and gaps in V2](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Azure-Functions-runtime-2.0-known-issues)

**Comment by jcbrooks92** [comment]
This is regarding the changes that are coming based on the templates created in VS. Is the function syntax going to be deprecated? Ie what I labeled as V1 templates.

**Comment by jeffhollan** [comment]
Yes we do need to improve some of our docs on new templates with v2. Assigning this to myself and @tdykstra and will triage in next doc sync.  In terms of deprecation, v1 will continue to exist for a considerable amount of time after v2 becomes GA.

**Comment by jcbrooks92** [comment]
Thanks Jeff!

**Comment by NichUK** [comment]
I just spent a little while trying to upgrade my function's app because of the error message:
"Cannot Upgrade with Existing Functions Upgrating the runtime version is also coupled with upgrades to languages and binding dependecies that may introduce breaking changes. Please create a blank function app to upgrade major versions of the runtime."
Firstly, you may want to correct the spelling of "Upgrating" and "dependecies", and then possibly add something to make it obvious that the templates have changed, and the functions themselves will need to be re-written. As I was unaware of the template change, I first thought that re-creating the functions project, and/or the app itself would be sufficient. Only when neither of those got rid of the message, did I go looking further (googling the error message was completely unhelpful), and discover the template change, and put two and two together. 
Maybe I'm just slow this morning, but it could be significantly more helpful, or link to a page that is.

**Comment by tdykstra** [comment]
@ggailey777 @SyntaxC4 FYI

**Comment by SoulFireMage** [comment]
I'm trying to decipher how to get rid of this warning myself - it's not clear to a novice at Azure functions at all.

**Comment by jeffhollan** [comment]
Closing as these docs are checked in and should publish soon
