### ISSUE TITLE
Add  the ability to load native c++ libraries (dll)

### ISSUE THREAD

**Issue by lukap3rcic** [Azure/Azure-Functions#68]
Add  the ability to load native c++ libraries (dll). Or even better; also add c++ language support with that.

I understand that this feature exceeds the scope of azure functions (for now), but there is a lot of c/c++ only libraries in crypto and other fields that could benefit from event driven and executed in self-regulating numbers of instances.

There is no other (fully managed "server-less") option for this in the market as of yet.

**Comment by lindydonna** [comment]
This should already work, but you'll have to use C# to reference the assemblies and use assembly import statements. Does this not work for you? 

If not, please paste the code you've tried and we can help troubleshoot.

**Comment by smlu** [comment]
Is C++/CLI dll wrapping supported? 
I've tried to run test cli dll on azure functions but it fails with an exception:
_` Exception while executing function: Functions.HttpTriggerCSharp1. mscorlib: Exception has been thrown by the target of an invocation. HttpTriggerCSharp1: Could not load file or assembly 'CS_CppAzureFunc, Version=1.0.6169.27417, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The specified module could not be found. mscorlib: Could not load file or assembly 'CS_CppAzureFunc.dll' or one of its dependencies. The specified module could not be found.`_
.

**Comment by lindydonna** [comment]
That could be an issue specific to the CLI having to do with path resolution. Does the same thing happen when running it in Azure?

**Comment by smlu** [comment]
This test was run directly in Azure, not locally. The Dll was compiled as CLR Class Library project in VS2015 then uploaded to azure and stored in bin folder of test function app.
Note : C# port of this test dll runs with no problem in azure

Function code:

```
#r "CS_CppAzureFunc.dll"
using System.Net;
using CSCppAzureFunc;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");

    // C++/Cli
    var test = new TestClass(1);  // These two lines throw an exception, if commented out it compiles successfully 
    var greetMsg = test.DoFunc();

    // parse query parameter
    string name = req.GetQueryNameValuePairs()
        .FirstOrDefault(q = > string.Compare(q.Key, "name", true) == 0)
        .Value;

    // Get request body
    dynamic data = await req.Content.ReadAsAsync<object>();

    // Set name to query string or body data
    name = name ? ? data ? .name;

    return name == null
        ? req.CreateResponse(HttpStatusCode.BadRequest, "C++ says:" + greetMsg)
        : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
}
```

DLL code:
```
// CS_CppAzureFunc.h
// This does not wrap any c++ dll yet
#pragma once
using namespace System;

namespace CSCppAzureFunc {
    public ref class TestClass
    {
    private :
        int mZ;
    public:
        TestClass(int z)
        {
            mZ = z;
        }

        String^ DoFunc();
    };
}
```

```
// This is the main DLL file.
 #include "stdafx.h"
 #include "CS_CppAzureFunc.h"

String^ CSCppAzureFunc::TestClass::DoFunc()
{
   return gcnew String("test");
}
```

**Comment by SharpDude** [comment]
Did you ever find a resolution for this? I am hitting the same issue. It just won't deploy the C++ DLL with the function when it gets published.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1470

**Comment by myusrn** [comment]
@smlu , @lukapercic , @lukapercic - any pointers to the secret steps to get a current generation vs17 "It Just Works]" / ijw c++ dll build with /clr settings outlined below to successfully load in an .net core/framework process space?  

I ask because when i reference and try and consume my ijw c++ /clr dll output from .net core/framework, ensuring i am matching dll platform type [win32/x64] with c# manage code consumer and process space, i get `Managed Debugging Assistant 'LoaderLock' : 'DLL '<path>\Dll2.dll' is attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'` and when I  uncheck LoaderLock option or dismiss and continue I always get `The program '[18348] testhost.x86.exe' has exited with code -532462766 (0xe0434352).` output window result.

I'd really like to get this working so I don't have to resort `#define DllExport extern "C" __declspec( dllexport ) ` approach in c++ native code dll and platform invoke [DllImport] in c# managed code function [ or other space.

```
<vs17 | visual c++ | windows desktop | dynamic link library project> | properties | configuration properties | c/c++ |
1. configuration = All Configurations and platforms = All Platforms 
general | common language runtime support = <unset> -> common language runtime support (/clr)  
code generation | enable c++ extensions = Yes (/EHsc) -> Yes with SEH Exceptions (/EHa)    
2. configuration = Debug and platforms = All Platforms
general | debug information format = program database for edit and continue (/ZI) -> program database (/Zi)  
code generation | basic runtime checks = Both (/RTC1, equiv. to /RTCsu) (/RTC1) -> Default  

```
