### ISSUE TITLE
Azure Functions v2 is labeled as "(.NET Core)" during template creation; it's .NET Standard

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/Azure-Functions#686]
The project creation wizard in Visual Studio labels Azure Functions v2 projects incorrectly as .NET **Core** projects when in fact they are .NET **Standard** ones.

#### Repro steps

1. Create a new Azure Function Project in Visual Studio 2017 (v15.5.6) with the latest SDK (v15.0.40108.0) as of this writing.
1. When picking the type of Function App, click the `Azure Functions v1 (.NET Framework)` dropdown
1. Choose a v2 function (labeled `Azure Functions v2 Preview (.NET Core)`)
![image](https://user-images.githubusercontent.com/20270743/36043116-0c106a5e-0d83-11e8-8998-337ef8b97286.png)

1. Note that, after creation, the function app targets .NET **Standard**, not .NET **Core**
![image](https://user-images.githubusercontent.com/20270743/36043213-61cd6a14-0d83-11e8-9fa2-f11060f4b171.png)

#### Expected behavior

The creation dialog should accurately convey the platform on which the resulting project will be created to target.

#### Actual behavior

Customers are getting confused as to whether or not the App is .NET Core or .NET Standard and are creating .NET Core libraries/shared code that cannot be reused in their Function apps due to this expectation.

![image](https://user-images.githubusercontent.com/20270743/36043354-eab5e5b8-0d83-11e8-9636-3c72fea6fbf8.png)

**Comment by brandonh-msft** [comment]
eg: #674

**Comment by paulbatum** [comment]
@ahmelsayed I think we've made it so that our feed has these display properties... can we update the feed appropriately so that once VS starts consuming it this is resolved?

**Comment by justcla** [comment]
We made a deliberate decision to re-label the ".Net Standard" option as ".Net Core" because it wasn't clear to users who wanted to work with .NET Core which item to choose. Perhaps we need to revisit that decision.

**Comment by MisinformedDNA** [comment]
These are my thoughts:

- If you want to build an library, you should try and target .NET Standard so that it can be (re-)used by 
 either the .NET Framework or .NET Core. Targeting .NET Framework or .NET Core is acceptable if you need the APIs, but it will limit reusability.
- If you want to build an app, you should target either the .NET Framework or .NET Core (or both). Targeting .NET Standard doesn't make a lot of sense for an app (though there may be exceptions) because .NET Standard doesn't contain a runtime, it's really just a contract of APIs. For this reason, you can't create a Console app that targets .NET Standard. The EF Core team also tried to work with .NET Standard for startup projects (and assume .NET Core), but abandoned it because it just doesn't work. (https://github.com/aspnet/EntityFrameworkCore/issues/8452 and https://github.com/aspnet/EntityFrameworkCore/issues/8349)

Also, calling something .NET Core and then using .NET Standard is really confusing to people who are new to all these new monikers. This should definitely be avoided.

If you need to support .NET Framework in Functions v2, maybe there should be three options in the initial dialog:
1. Azure Functions v1 (.NET Framework)
2. Azure Functions v2 (.NET Core)
3. Azure Functions v2 (.NET Framework)

But with that, because Functions will run in the cloud, I feel like we should nudge users in the direction of Option 2 by default.

**Comment by brandonh-msft** [comment]
@justcla And that's cool. The resulting Fxn project, then, should be a .Net Core project - but it's not :)

**Comment by brandonh-msft** [comment]
⏲

**Comment by sonphnt** [comment]
I think at some point we should remove the concept .Net Standard to avoid confusing to everything. 

.Net Framework 4.x => legacy
.Net Core 2.x => new generation works on multi platforms

No more .Net Standard or other things. Visual studio should be smart enough to eliminate unnecessary components or runtime

So if you are creating a library project. All unnecessary component related to runtime should be ignored

**Comment by soninaren** [comment]
This is fixed now. Update the visual studio extension to version 15.0.40502.0. (Tools -> Extensions and Updates -> Updates -> Azure Functions and Web Jobs Tools).

**Comment by pscholtes** [comment]
@soninaren What was the fix exactly? I don't think a clear resolution path was identified here. With version 15.0.40502.0, the "Azure Functions v2 Preview" now lists .NET Standard as the target framework and .NET Core is no longer listed. Also, referencing a project that targets .NET Core 2.x produces the expected "project not compatible" build error.

So it looks like we should migrate our library projects from .NET Core to .NET Standard so they can be leveraged in Azure Functions projects like @MisinformedDNA and @brandonh-msft discussed? Any word on whether or not an Azure Function app will support the .NET Core target framework in the future?

**Comment by sonphnt** [comment]
People is interested in .Net Core 2.1. Please make this available for it. 

At some point, please remove the concept .Net Standard out of Microsoft system. 

.Net Core will be used in all platforms. The legacy Net Framework 4.7 should be removed as well. So 1 framework for everything i hope

**Comment by MisinformedDNA** [comment]
I agree with @pscholtes, the wrong fix was made. .NET Core is a runtime. .NET Standard is just a contract. The user should be choosing which runtime they want, not which contract they want.

You don't create a Console app targetting .NET Standard, you have to target .NET Core, because you need a runtime!

Also, tools like EFCore won't work on .NET Standard, because again, it needs a runtime.

@soninaren is there another repo tracking/discussing this?

**Comment by paulbatum** [comment]
Hi! There are a few assertions being made on this thread that seem a little off based on the unusual nature of Azure Functions so I want to try to clear a few things up.

An Azure Function app is not like a console app. You don't own Main(). In the case of C#/F#/etc, you write your application as a set of DLLs and they are run within OUR runtime. Go ahead and open a function app in VS, hit F5, then look at the process that is running - it doesn't come from your bin folder. Do the same thing in Azure and you'll see that the entry point does not come from your application's file system. Based on the versions of functions you pick, WE pick the runtime that is used.

When you make a function app in VS, the tooling is asking you to pick a version of Functions. Literally we are asking you "V1 or V2". We have some additional text in the dropdown to help the user understand what they are getting. This entire issue is about which version of that additional text is most useful. Given enough space on the screen, the most accurate thing to say would be "Functions v2 Preview (targeting .NET Standard 2.0, running on .NET Core 2.x)". I am not sure that this level of verbosity is required when really all we want the user to do is select a version of Azure Functions.

If you want to request that VS provides tooling for authoring functions as a .NET Core class library instead of a .NET Standard class library, please do that in another issue (in this repo) as that is a feature request and is not about the text this screen shows.

If you want to request that the functions team provides the ability to run Functions V2 on .NET Framework, please see this issue and comment there:
https://github.com/Azure/Azure-Functions/issues/790

If you want to request that Microsoft deprecates the concept of .NET Standard, please do so elsewhere.. that has nothing to do with Functions and is not useful discourse to be held here.

**Comment by pscholtes** [comment]
Thank you, @paulbatum -- this is exactly what I was looking for. As requested, I will create a new feature request regarding .NET Core class library support in AF.
