### ISSUE TITLE
Visual Studio is not uploading all my files

### ISSUE THREAD

**Issue by ssougnez** [Azure/Azure-Functions#695]
Hello,

I have an "Azure Functions" project with the following structure:

![vstudio](https://user-images.githubusercontent.com/10199821/36863895-4d3166ba-1d8b-11e8-9b2d-0424d679fb5d.png)

When I right click on the project and chose "Publish", only JSON files get uploaded to the "Azure app service" therefore, Azure tells me that there is no function currently present.

I tried to run "func azure functionapp publish my-azure-jobs" and this time it worked well although the "node_modules" of the "Shared" folder got uploaded as well (as a matter of fact, ALL files got uploaded). Shouldn't it be somehow excluded and packages restored automatically?

I'm using Visual Studio 15.6.0 Preview 6.0 and the "Azure Functions and Web Jobs Tools" package is 15.0.40215.0.

**Comment by ahmelsayed** [comment]
For VS publishing:
   can you make sure all your files are set to `Copy to output`? 

For CLI publishing:
Yes the `func azure functionapp publish` will package all the local files with [some default excludes](https://github.com/Azure/azure-functions-core-tools/blob/v1.x/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionApp.cs#L147). Namely `[ ".funcignore", ".gitignore", "appsettings.json", "local.settings.json", "project.lock.json" ]`

The cli also supports `.funcignore` file which has the same semantics as `.gitignore` and only takes effect in publishing. If you wanna use the `func azure functionapp publish` command and want to exclude some files, add those to your `.funcignore`

However it's worth mentioning that you want things like `node_modules` in the package you're publishing because the server won't restore these packages for you. `.funcignore` was added for other files that don't affect your functions runtime. see this issue for more details https://github.com/Azure/azure-functions-core-tools/issues/341

**Comment by ssougnez** [comment]
Okay, so I updated my files properties and set "Copy to output" on "Only if newer" and it did work. However, I can't do that for the "node_modules" folder as it is a folder, so it does not get copied to Azure. 

If I understand well, the packages used by Azure are the one installed on development as these ones are uploaded and not automatically restored by Azure? It makes sense although it could be a bit problematic sometimes. Indeed, with big projects, you can have a very big "node_modules" folder (with all the dependencies...).

It's good to know that a ".funcignore" file is supported, I might use it someday. However, you told me about the default exclude. Is it only for the "func azure functionapp publish" command or also for Visual Studio ? Because I just checked and Visual Studio uploaded the "local.settings.json" file while the command did not.

Another question a bit off topic. Why is it that we have to create a specific project for functions ? I tried to use the "func azure functionapp publish" on a simple folder that contained multiple functions and it worked very well. I find it a bit restrictive to be forced to use a separate project to be able to create/publish function via VS.

Thanks for your quick answer ;-)

**Comment by ColbyTresness** [comment]
@nimakms to answer above

**Comment by ColbyTresness** [comment]
@soninaren to provide explanation and close

**Comment by ColbyTresness** [comment]
@soninaren ping

**Comment by soninaren** [comment]
@ssougnez 

> Another question a bit off topic. Why is it that we have to create a specific project for functions ? I tried to use the "func azure functionapp publish" on a simple folder that contained multiple functions and it worked very well. I find it a bit restrictive to be forced to use a separate project to be able to create/publish function via VS.

Visual studio does not support full development and integration story without a project/ sln file. However we do have support for that in Visual studio Code. VS Code does not force you to create a sln/ project. Integrates with the Functions CLI and provides a debugging experience as well. The reason we you have to create specific projects for functions in Visual Studio (not code) is because VS uses the dotnet templating engine to manage all the applications. The dotnet templating engine is modeled to use Project and item templates to support app development specially for apps targeting dotnet.
