### ISSUE TITLE
Polling costs with Service Bus Queue triggers

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#714]
The message pump driving a Service Bus Queue trigger generates an endless series of requests against the queue. I had noticed this awhile back and [this](https://stackoverflow.com/questions/49263448/understanding-azure-function-app-and-service-bus-costs) question on SO reminded me to go back and take a look.

I created a new resource group and added a new service bus and function app, then added the default CSX queue trigger code (e.g. it just logs the message). If I run the trigger once from the portal, the function runs, then if I refresh the queue stats, there are hundreds of requests generated after just a minute or so. Here the function had only been running a few minutes, it looks like maybe several requests per second:

![image](https://user-images.githubusercontent.com/794270/37369086-74905228-26de-11e8-8f4f-714e3df588c6.png)

Over in my "realistic" system (experimentation with MSDN sub) this is shown as millions upon millions of requests against my service bus from just a few queues over the course of a month (it's actually coming close to blowing out my MSDN subscription credit with little or no other activity generating billable costs). 

Is there a way to control this? Even a single low-frequency queue wastes quite a lot of money, and this strikes me as inconsistent with the demand-driven concept of the Function App Consumption Plan. (Polling also strikes me as a bit brute-force primitive.)

**Comment by MV10** [comment]
Zero activity other than the Function waiting for messages... 14 hours later, 72,000+ requests and ~$20 burned doing nothing.

![image](https://user-images.githubusercontent.com/794270/37396841-6a33d1ca-2750-11e8-965c-24a21bd0c524.png)

**Comment by lewan0996** [comment]
Hello @MV10 , did you manage to solve that issue? I've just started to use queue and topic triggers which generate thousands of requests while actually doing nothing.

**Comment by MV10** [comment]
@lewan0996 Nope. I wrote my own and (reluctantly) stopped using Service Bus Queues. I really like Azure but it feels like there are a lot of features that are only useful if you have Enterprise-grade deep pockets (and a boss that won't beat you up if a bug suddenly chews through ten million messages while everybody is out for the weekend).

**Comment by lewan0996** [comment]
Maybe we could achieve the same thing by using the event grid which could fire the function by http when it receives the message from service bus. Of course it will work only if event grid does not poll the queue as the service bus trigger does. I will try this approach, or even without service bus at all, only with event grid

**Comment by harleydk** [comment]
@lewan0996 I'm just about to try that out as well - how did it work out for you? My source of inspiration is https://medium.com/@jeffhollan/why-event-grid-is-a-game-changer-for-serverless-8979870a65d1, perhaps helpful to you as well.

**Comment by MV10** [comment]
I also intend to review third-party options like RabbitMQ. Surely someone is doing true push. The project that prompted this thread is already fixed on our custom solution but I know it will come up again. @harleydk Thanks for the heads up about Topics, looking forward to info about Event Grid -- although I think I've read the payload is very tiny due to its intended massive-scale IoT use-case (could be wrong about that, though, haven't really looked at it at all).

**Comment by lewan0996** [comment]
@harleydk Unfortunately it turns out that Service bus can be connected to the Event Grid only if it's scaled up to the premium plan, which is not an option in our project. However, my main concern at the beginning was the cost of so many useless requests to the service bus. 

> 72,000+ requests and money burned doing nothing. @MV10 

I intentionally left the Service bus running with couple of functions triggered by it which resulted in generating hundreds of thousands of those requests, but I was charged literally nothing as if it was just irrelevant to the pricing. I agree that the way those triggers work is disappointing, but as long as it works and does not burn money - I can live with that.

 @MV10  It's weird that you had experienced such rate of spending the money. Maybe there were some changes in the way they calculate the cost? I wouldn't like to wake up one day and see the biggest bill ever all of the sudden. Is it possible that you try to setup those functions again?

**Comment by MV10** [comment]
@lewan0996 I was thinking about this, too (isn't there something like 1 million free hits per month? I haven't reviewed the rate plan for quite awhile now)... I'm wondering if the spend was actually a side-effect of some logging that was left running or something similar. Really hard to decipher their billing statements. (It's also possible I ran over the free million, earlier I ran tests that involved tens of thousands of hits ... which become hundreds of thousands if something goes wrong and the 10X retry kicks in!

Regardless of what was going on, the pricing model for anything but the most basic DIY features seems pretty hard to swallow at the small- to medium-size business level.

**Comment by harleydk** [comment]
@lewan0996 I did what you did and left the Service bus running, and was charged sufficiently as to worry about future spending. I had, still have I guess, problems in evaluating the cost. The Service Bus was a standard, not premium, so it could be that the cost I saw was maybe related to the monthly cost being distributed across the individual days of use. I'm not 'getting' the pricing model, but I have not made a huge effort in trying to, either - I stopped somewhat short of trying when I came upon the huge number of requests and needed to understand the reason for that, first.

@MV10 I agree with you on your thoughts on the pricing model. I was feeding the Service Bus from a number of Azure Functions, and also used Azure Functions as topic subscription triggers - hence my high request count. I have come to realize that for a small- to medium-size business level, I'm likely better off with running Azure Functions within an app service using queue storage in lue of a service bus , where the cost is fixed and the number of requests do not matter, or at least influence the cost in a volatile fashion (so to speak). Performance is largely the same, and in due time I'll likely introduce a service-bus implementation in a VM, where I can be certain of the cost, rather than rely on the dedicated Azure offerings. I'm thinking there's certainly a business model for the Service Bus, but it's probably related to far grander use-cases than meets my desk. 'True push' is something of an illusion, there has to always be an associated CPU cost related to the ability of receiving a push notification, akin to polling. But, yea, I agree that the cost shouldn't be high, and given an improved Azure billing statement I'd be more inclined to use the products. The pricing model might even be very reasonable, it's just that I can't really tell and so shy away from it.

**Comment by mrwatts** [comment]
This actually isn't an issue within the Azure WebJobs. It's because of how the Service Bus MessageReceiver works. MessageReceiver.RegisterMessageHandler is used, which creates a message pump. Everytime a message is received, the handler is invoked. 

Internally, the MessageReceiver starts a ReceiveAsync. A polling model was chosen in order to enable load leveling. So, if there isn't a message waiting, it will wait until the timeout is reached. Then it will retry. You can find some more details about it [here (link to social.msdn)](https://social.msdn.microsoft.com/Forums/en-US/86a07793-6dcf-4e9f-8448-4eab611b3836/how-to-receive-message-from-azure-service-bus-queue-without-polling-a-queue?forum=WAVirtualMachinesVirtualNetwork).

Quote from that thread: 

> The trick to keeping your costs down is to set long-ish time-out on the Receive/OnMessage method. The Default = 60 secs.

You can set the time out in the service bus connection string, e.g. 2 minutes:

`Endpoint=sb://<yourservicebusinstancename>.servicebus.windows.net/;OperationTimeout=00:02:00;SharedAccessKeyName=<keyname>;SharedAccessKey=<key>`

I'm not yet sure if this has the desired effect. I only implemented this myself this morning. There appeared to be an immediate drop for a few hours, but total request count over a week or month will be more indicative.

**Comment by harleydk** [comment]
@mrwatts Tough, but thanks for reporting back on it, saves me a bit of time. Just out of curiosity, what's your alternative strategy, if any?

**Comment by mrwatts** [comment]
@harleydk Well, I've looked a little further into the matter and conducted some tests, which have lead me to the conclusion that this issue is actually a bug. So the alternative strategy is to get the team to fix the bug. I've created a new issue explaining the problem [here](https://github.com/Azure/azure-webjobs-sdk/issues/1690)

**Comment by amrbadawy** [comment]
@mrwatts did you find any good solution ?
