### ISSUE TITLE
DocumentClient binding by connection string stopped working.

### ISSUE THREAD

**Issue by vprovalov** [Azure/Azure-Functions#716]
Hi, I am binding Document DB client with:

[DocumentDB(ConnectionStringSetting = "<connection string>"]DocumentClient documentClient

This used to work with Microsoft.Azure.DocumentDB 1.13.2 (required by Microsoft.Azure.WebJobs.Extensions.DocumentDB 1.1.0), but after upgrading to version 1.21.1 I see following error:

Microsoft.Azure.WebJobs.Extensions.DocumentDB: 'Id' is required when binding to a DocumentClient property.

**Comment by paulbatum** [comment]
In order to be able to use DocumentDB bindings, you'll have to stay on version 1.13.2.  If you reference newer versions of the library, functions won't recognize the DocumentDB types in your code.

This general class of issue is tracked here:
https://github.com/Azure/azure-functions-host/issues/992

Closing this as a duplicate.
