### ISSUE TITLE
Need a way to detect total function failure in Application Insights

### ISSUE THREAD

**Issue by Ryanman** [Azure/Azure-Functions#748]
Hi all. Opened an issue ([227](https://github.com/Azure/azure-functions-durable-extension/issues/227)) today with durable functions based on their catastrophic prod break with the runtime updated, related to issue [210](https://github.com/Azure/azure-functions-durable-extension/issues/210).

As I mentioned in 227 I understand that we're taking a risk using V2 of the functions, but this huge failure cut down our function collection and we recieved no notice from (enabled) Application Insights.

I attempted to make a classic alert based on the number of times a function ran (if >=1 in the past period then send an email) but it looks like this metric is broken. In this screenshot dozens of function executions are occuring but it looks like that's not being captured. 

![image](https://user-images.githubusercontent.com/1376624/38327814-379e1d56-3817-11e8-8b5c-bd46e1854b01.png)

Even attempting to create it fails.
![image](https://user-images.githubusercontent.com/1376624/38328019-bf8de53e-3817-11e8-9259-d1c6f41a4daf.png)

Do you have any suggestions to cover a failure this fundamental where the function host can't even start?

Thanks for your help.

**Comment by Ryanman** [comment]
Perhaps the closest thing to this is using an Availability test for the top-level function endpoint?

**Comment by paulbatum** [comment]
Hi there, I'm not an expert on using the alerts UX and I do not understand the error you got, but I have a few observations:

1. It seems that the Function Execution Count metric is not populated for function apps on a dedicated app service plan. Perhaps the error you are getting is related to this. I have created a separate issue to track this problem:
https://github.com/Azure/Azure-Functions/issues/750

2. I thought this was doable using an alert based on the built in metrics provided by App Insights such as the Server Requests (count). But I can't see any applicable metric in the dropdown when creating the alert. The metric `request rate` doesn't seem to apply - there's no data for a function app.

3. I thought it would be possible to work around this by creating an alert based on the custom metrics that Azure Functions writes to App Insights.  However when I tried this out myself, **it did not work**. Here's what I attempted:

![image](https://user-images.githubusercontent.com/10663/38340519-c7c71728-3828-11e8-8806-4a7bcd628659.png)

![image](https://user-images.githubusercontent.com/10663/38340523-cd933b28-3828-11e8-9f73-1ea528da75b7.png)

As far as I can tell, it didn't work because the alerting system does not treat the *absence* of a metric as a zero. I'm asking around for some advice on how to address this.

**Comment by paulbatum** [comment]
I should note that an alert based on the `exception rate` metric could have probably caught the particular issue that impacted you, but its not a great/general solution because it doesn't help in the cases where the system is silently doing nothing. So I think the focus should still be on how to create an alert when execution count hits goes to zero.

**Comment by Ryanman** [comment]
@paulbatum Thanks for your in-depth reply. I think the general "Availability Test" at the base API URL for a function app _does_ accomplish what I want in terms of catastrophic failure test. It'll even catch if I stop the functions manually.

But the information both you and I have described - namely that there are multiple metrics that aren't functional for these apps - is kind of a let down. I do want to note that in my particular case these function apps **are** on their own service plan as you suspected. Thanks for opening an issue in this regard.

**Comment by jeffhollan** [comment]
@Ryanman I've had success with App Insights alerts in the past. It's also very flexible and you can write complex queries to trigger alerts.  So in screenshot below I have a simple "if Exceptions > 0 over 5 minutes" fire an alert, but I could do alerts on specific traces or exception text.  Hope that helps

![2018-04-05 14_50_51-configure signal logic - microsoft azure](https://user-images.githubusercontent.com/7132626/38393829-fb05ecb4-38e0-11e8-95f3-4cd575c751a4.png)

**Comment by ColbyTresness** [comment]
Closing unless there are any objections.
