### ISSUE TITLE
Visual Studio can't launch or publish Azure Functions projects

### ISSUE THREAD

**Issue by kagetoki** [Azure/Azure-Functions#777]
On attempt to launch AF project studio shows error message, that it can't run a class library.
Also, unlike web projects, it does not suggest to publish functions to azure.

Can be reproduced on at least MSVS 2017 Professional 15.6.6 and Community 15.5.3
Azure functions and Web Jobs tools version is 15.0.40215.0

**Comment by sergey-litvinov** [comment]
It happens for me too. Visual Studio 2017.7.1 and it doesn't show Publish option for Function App project and i saw documentation in azure docs that says that you can publish it from Visual Studio

**Comment by mario-bless** [comment]
Same here! Interestingly, it did work fine. After installing Nuget Microsoft.Azure.WebJobs.Extensions.DocumentDB to write data to CosmosDb - project was not able build anymore because of version conflicts within dependencies. By fixing that problem - it seems somehow did destroy this functionality to deploy to azure. Also, I can not debug the azure functions locally anymore (can't run class library), which was fine working before. Furthermore - I can add Azure Functions App to a solution (which includes one function), however I can not add a new azure function (no template available) to azure function app anymore. Even a repair of the Visual Studio installation could fix that problem. So bizarr, like I said it was working properly - suddenly nothing works anymore.
Versions:
Microsoft Visual Studio Professional 2017: 15.7.5
Azure Functions and Web Jobs Tools: 15.0.40617.0
Fast help would be highly appreciate, since I do not have any clue what is wrong...

**Comment by ColbyTresness** [comment]
@nimakms for VS integration

**Comment by ColbyTresness** [comment]
I think this has been improved. Please reopen if its still an issue you're seeing.
