### ISSUE TITLE
C# Parallel.ForEach not excuting in parallel

### ISSUE THREAD

**Issue by sacunningham** [Azure/Azure-Functions#815]
I have a C# Azure Function running the following code.

`var act = new Action<T>((i) =>
				{
					//===DO WORK==
				});
Parallel.ForEach(listItem, act);
`

When testing the code locally using the Azure Functions Tools CLI this code does execute in parallel.  However, when the function is published to a Azure Function App (running on a consumption plan) the code executes syncronously.  Is this the expected behavior or am I missing something?

**Comment by paulbatum** [comment]
This is basically expected behavior as the level of asynchrony you'll get will depend on the number of cores the machine has, and you can't control that when you're deployed to the consumption plan. 

The dynamic scale capabilities of Azure Functions will never take a single execution and transparently distribute that execution over multiple threads or machines. If you have a scenario where a large amount of work has to be done based on a single event then you should split your work up across multiple function executions so that the system can scale it out. One of the easiest ways to do this is with queues.
