### ISSUE TITLE
Creating 2 consumption apps in same resource group fails.

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#853]
Message:
The requested app service plan cannot be created in the current resource group because it is hosting linux apps.

**Comment by bala16** [comment]
Only repros when creating the app from portal since portal calls 

POST https://management.azure.com/subscriptions/SUBSCRIPTIONID/resourcegroups/RESOURCEGROUPNAME/providers/Microsoft.Web/validate?api-version=2016-03-01

{
"location": "West Europe",
"name": "8280",
"properties": {"skuName": "Y1"},
"type": "Microsoft.Web/serverfarms"
}

This is trying to validate creation of windows app in linux app resource group. (which is not supported)

The request body should instead be
{
"location": "West Europe",
"name": "8280",
"properties": {"skuName": "Y1", **"needLinuxWorkers" : true**},
"type": "Microsoft.Web/serverfarms"
}

tracked by https://github.com/Azure/azure-functions-ux/issues/3277

**Comment by balag0** [comment]
fixed
