### ISSUE TITLE
Function Type Name Invalid

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/Azure-Functions#889]
Getting,

```
Error:

Function (CommonServiceBusDLQueueTrigger) Error: The function type name 'CommonGatewayFunction.CommonServiceBusDLQueueTrigger' is invalid.
Session Id: 12e8f71438644d5f883984c1119518aa

Timestamp: 2018-07-13T06:31:42.360Z
```
After deploying the pre-compiled function via Zip push. Length of "CommonGatewayFunction.CommonServiceBusDLQueueTrigger" is 52. According to https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions, a function app's name could be 1-60 chars in lenght but what is the limitation for a function inside a function app?

I works if I reduce his length by two characters (eg: CommonServiceBusQueueTrigger).

PS : Names of the function app and function are anonymized. But the session id is same (in case if it is useful for debugging at your end).

**Comment by kashimiz** [comment]
Hi Isham, how are you generating your function.json files? Are you using Visual Studio and attributes, or updating your function.json by hand?

**Comment by IshamMohamed** [comment]
As I mentioned its precompiled function. So its, using Visual Studio and attributes

**Comment by kashimiz** [comment]
Right, thank you. So this is a function _type name_ error, which is different from a function naming error. It means the Functions runtime is unable to find a type with your function's name in the assembly that you're using. This is the type that goes in your function.json for precompiled functions.

Could you check the function.json for your function, as well as the assembly you're using? function.json should be in /bin/{FunctionName} folder of your solution.

**Comment by IshamMohamed** [comment]
I tried to recreate this again - but now it seems the problem no more exist. I am closing this issue.

**Comment by kashimiz** [comment]
@bartdk-be You can set the name of your function using the `FunctionName` attribute in precompiled functions, like so:

```csharp
public static class FunctionClass
{
    [FunctionName("Function1")]
    public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = 
  null)]HttpRequestMessage req, ILogger log)
    {
        // function body
    }
}
```

By default, functions will have the name of their method, but you can override that using the `FunctionName` attribute. So in the example above, the function name will be `MyFunction` instead of `Run`.

The build process for precompiled functions [generates `function.json` files from attributes.](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#autogenerated-functionjson) The above function would generate a `function.json` in the `/bin/MyFunction/` subdirectory of your app like so:

```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.24",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "post"
      ],
      "authLevel": "function",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/VSSample.dll",
  "entryPoint": "VSSample.FunctionClass.Run"
}
```

Note that while the name of the subdirectory determines the function's name, the host still needs to know the entry point into the code. That's the purpose of the `entryPoint` field in the `function.json`. If the listed `entryPoint` doesn't correspond to an actual type in your binaries, the Functions host will generate the error reported by the original poster.

As stated in the documentation, we don't recommend editing these generated `function.json` files yourself. So in short, control your function name using the attributes.

**Comment by IshamMohamed** [comment]
> @IshamMohamed : Did you change anything to fix this error ?
> I'm still getting the error with the latest

I did not change any thing and all of the sudden I have noticed that it started to work. Did you try reducing the length of the name?

**Comment by badcop666** [comment]
I have this problem currently. I have resorted to deleting the function app service and recreating it.
This is poor - zero indication of what the problem is. 
If this is caused by some sort of naming conflict between previously deployed functions and renamed or added functions - then I am unimpressed - since this is something that happens every single day during development.
I would like to see a Microsoft response to this, suggestions for resolution or workaround, and timeframe for permanent fix or improvement in error messaging.

**Comment by Dan-cws** [comment]
It seems to be a transient error. Try restarting your function app service as it said here https://github.com/Azure/Azure-Functions/issues/541
It worked for me.

**Comment by jeremiah-s-eldridge** [comment]
For me - I updated to functions v2, but still had an ARM template that had the FUNCTION_EXTENSIONS_VERSION set to ~1 instead of ~2

**Comment by dhabierre** [comment]
Same issue using Terraform.
This code works:

```hcl
resource "azurerm_function_app" "function_app" {
  ...
  version = "~2"
}
```

**Comment by euangordon** [comment]
Just had the same issue with a v3.0.5 Azure Function. I published the same Azure Function to two environments, in test it worked fine but in live I got:

"The function type name 'Compass.AIS.AisUpdateCacheTimer' is invalid. 

Turning the function off and on again resolved the issue.
